% !Rnw root = master.Rnw
%! TEX root = master.tex
\Sexpr{knitr::set_parent('master.Rnw')}


\section*{Key Points}
\textit{Question:} Does a short, animated entertainment-education (E-E) video improve knowledge of
COVID-19 prevention behaviors?

\textit{Findings:} The E-E video significantly increased our primary endpoint, and
demonstrated effectiveness by boosting already high knowledge of COVID-19 prevention
behaviors. 

\textit{Meaning:} Given good engagement with the intervention video, our results support the use
of E-E media on social media platforms to disseminate evidence-based health
recommendations related to COVID-19 as well as other public health emergencies.





\subsection*{Abstract}


\textbf{Background:} Correct knowledge of COVID-19 prevention behaviors is critical for
epidemic control in the absence of a vaccine.  To improve COVID-19 prevention knowledge,
we have designed a short, animated entertainment-education (E-E) video that can be rapidly
distributed through social media channels to a global audience.  We measure the
effectiveness of the E-E video in an online setting using a randomized controlled trial
(RCT). 

\textbf{Methods:} Between \Sexpr{res$dates[1]} and \Sexpr{res$dates[2]}, we used an online
platform to enrol \Sexpr{fmt(flow$In)} adults from the United States of America, Mexico,
United Kingdom, Germany, and Spain.  Participants were randomized 1:1:1 to one of three
trial arms: (i) the E-E video, (ii) an attention placebo control (APC), and (iii)
do-nothing.  Our pre-specified primary endpoint was the correct response rate to 18
questions about preventive COVID-19 behaviors.  This trial was registered at the German
Clinical Trials Register (DRKS) under \#DRKS00021582. 

\textbf{Findings:} Knowledge in the E-E video arm  was significantly higher (mean $=$
\Sexpr{fmt(know_res$means["VideoArmTreatment"], 2)}; 95\% CI:
\Sexpr{fmt(know_res$cis["VideoArmTreatment", 1], 2)},
\Sexpr{fmt(know_res$cis["VideoArmTreatment", 2], 2)}) than the APC  (mean $=$
\Sexpr{fmt(know_res$means["VideoArmPlacebo"], 2)}; 95\% CI:
\Sexpr{fmt(know_res$cis["VideoArmPlacebo", 1], 2)},
\Sexpr{fmt(know_res$cis["VideoArmPlacebo", 2], 2)}; \Sexpr{know_res$contdiff$pval}) and
do-nothing (mean $=$ \Sexpr{fmt(know_res$means["VideoArmControl"], 2)}; 95\% CI:
\Sexpr{fmt(know_res$cis["VideoArmControl", 1], 2)},
\Sexpr{fmt(know_res$cis["VideoArmControl", 2], 2)}; \Sexpr{know_res$totdiff$pval}) arms.
Baseline knowledge in the do-nothing arm was high, with a
\Sexpr{fmt(know_res$means["VideoArmControl"]/18 * 100, 1)}\% correct response rate.  In
the non-intervention arm, \Sexpr{round(watched*100, 0)}\% of participants chose to view
the E-E video and \Sexpr{round(less150*100, 0)}\% of these participants viewed the entire
E-E video.


\textbf{Interpretation:} The E-E video significantly increased our primary endpoint, and
demonstrated effectiveness by boosting already high knowledge of COVID-19 prevention
behaviors. Given good engagement with the intervention video, our results support the use
of E-E media on social media platforms to disseminate evidence-based health
recommendations related to COVID-19 as well as other public health emergencies. 

\clearpage
