% For LaTeX-Box: root = master.tex
% !Rnw root = master.Rnw
\Sexpr{knitr::set_parent('master.Rnw')}

\clearpage


\subsection*{Figures}
\label{sub:Figures}


\begin{figure}[!ht]
\centering
\includegraphics[scale=0.6]{DataFlow1.png}
\caption{Trial design.}
\label{fig:dataflow}
\end{figure} 


\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.26]{forestknow.png}

\caption{Shows the proportion of correct answers for each knowledge item by arm.}

\label{fig:forest}
\end{figure} 

\renewcommand{\note}{%
Mean differences between the E-E video, Attention Placebo Control (APC), and do-nothing
arms are reported with p-values.  Total effect represents
the difference in means between the E-E video and the do-nothing arm; Attention effect represents
the difference in means between the APC and do-nothing arm; and Content effect represents
the difference in means between the E-E video and the APC arm.  }

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.80]{KnowledgeAll.png}

\caption{Mean score for the COVID-19 knowledge questions by trial arm ($N= $\Sexpr{fmt(flow$FinalN)}).   \note    }

\label{fig:knowall}
\end{figure} 


\clearpage



