% !Rnw root = master.Rnw
%! TEX root = master.tex
\Sexpr{knitr::set_parent('master.Rnw')}

<<echo=FALSE>>=
fmt <- function(x, d=0) formatC(x, format="f", digits=d, big.mark=",")
@



<<echo=FALSE>>=
adiff <- res_all$means["VideoArmTreatment"] - res_all$means['VideoArmControl']
adiff2 <- res_all$means["VideoArmTreatment"] - res_all$means['VideoArmPlacebo']
an <- length(c(sstate, cstate))
amax <- an - res_all$means["VideoArmControl"]
amax2 <- an - res_all$means["VideoArmPlacebo"]
acorrect <- res_all$means["VideoArmControl"]/an*100
@


<<echo=FALSE>>=
kdiff <- res_know$means["VideoArmTreatment"] - res_know$means['VideoArmControl']
kdiff2 <- res_know$means["VideoArmTreatment"] - res_know$means['VideoArmPlacebo']
kn <- length(cstate)
kmax <- kn - res_know$means["VideoArmControl"]
kmax2 <- kn - res_know$means["VideoArmPlacebo"]
corrects <- res_know$means["VideoArmControl"]/kn*100
@


<<echo=FALSE>>=
kns <- length(sstate)
kmaxc <- kn - res_spr$means["VideoArmControl"]
correctc <- res_spr$means["VideoArmControl"]/kns*100
@

<<echo=FALSE>>=
fmtCI <- function(x) {
  dd <- behav[rownames(behav) %in% x, ]
  ci <- paste0("95\\% CI: ", dd["LB"], "--", dd["UB"], "\\%")
  mn <- paste0(dd["Est"], "\\%")
  return(list(both = paste0(mn, ", ", ci), mn=mn, ci=ci))
}
@



\subsection*{Abstract}


\textbf{Background:} Entertainment-education (E-E) media can improve health knowledge and
reach millions of people without requiring any physical contact. We have designed a short,
wordless, animated video about preventative COVID-19 behaviours---such as social distancing
and frequent hand washing---that can be rapidly distributed through social media channels
to a global audience. The E-E video's effectiveness, however, remains unclear.  

\textbf{Methods:} This multi-site, parallel group, randomized controlled trial compared
the effectiveness of an E-E video on COVID-19 (CoVideo) against  an attention placebo
control (APC) video and  no video (control). Using an online platform, we recruited
participants aged 18--59 years from the United States, the United Kingdom, Germany, Spain,
and Mexico.  The main outcome measure was knowledge about the basic clinical aspects of
COVID-19 (clinical knowledge, 10 items)  and knowledge of behaviours that prevent COVID-19
spread (knowledge spread, 8 items). 


\textbf{Findings:} We recruited \Sexpr{fmt(flow$In)} online participants between
\Sexpr{res$dates[1]} and \Sexpr{res$dates[2]}. The final analysis included
\Sexpr{fmt(flow$In - flow$Start)} participants randomly assigned to the Control
(\Sexpr{fmt(flow$CtrlN)}) APC (\Sexpr{fmt(flow$APCN)}), and CoVideo
(\Sexpr{fmt(flow$CoVidN)}) arms.  Knowledge in the Control arm was high: participants
correctly answered \Sexpr{fmt(corrects, 1)}\%  of the clinical knowledge questions,
\Sexpr{fmt(correctc, 1)}\% of the knowledge spread questions, and \Sexpr{fmt(acorrect,
1)}\% of the combined (18) items. Combined knowledge was higher in the CoVideo arm, with
greater clinical knowledge gains in older participants (45--59 years).  Adjusting for
demographic factors, knowledge scores were higher among women, more educated participants,
and German speaking residents. 


\textbf{Interpretation:} In a large, online randomized controlled trial, we found high
levels  of COVID-19 knowledge. Even with these high baseline levels, the CoVideo was
effective in increasing basic clinical knowledge about COVID-19.  Our results support the
use of E-E media on social media platforms to improve COVID-19 knowledge at global and
rapid scale without requiring physical contact. 

\textbf{Funding:}
This study is funded by the Alexander von Humboldt University Professor Prize.


\clearpage

\subsection*{Introduction}

A large amount of published health information about the novel coronavirus (COVID-19) has
been disseminated by the traditional mass media since the outbreak of the
pandemic.\autocite{Cinelli2020,Kouzy2020,Mian2020a} However, it is not clear if this
information has improved knowledge of preventative COVID-19 behaviours. By preventative
behaviours, we mean the public's adoption of practices such as social distancing, reduced
physical contact, and hand sanitation (among others) that can prevent the spread of
COVID-19. 

Arguably, one possible limitation of mainstream mass media is that it has been perceived
as politicized and culturally localized, thus limiting the persuasiveness of health
messages about COVID-19.\autocite{Garfin2020a, Garrett2020} It is also likely that
traditional mass media channels (e.g., local or national television networks) have missed
key segments of the population, such as young people (18--35 years) who are
disproportionately more likely to transmit the virus to older people ($\geq$ 50
years).\autocite{Dowd2020, Harris2020, Zhao2020} An effective public health response could therefore benefit
from entertainment-education (E-E) approaches that focus on
behaviours to prevent COVID-19 spread.\autocite{Hahn2020, Block2020} 

To improve knowledge about preventative COVID-19 behaviours, we have designed a wordless,
animated video (abbreviated to CoVideo) that can be rapidly distributed to a diverse and
global audience through social media channels.\autocite{Adam2020} With a short duration
(approximately 2.30 minutes), the CoVideo contains no speech and minimizes cultural
signifiers to increase universality and appeal. The CoVideo was released on Stanford
Medicine's YouTube channel on March 21, 2020, and went viral within 24 hours.  After ten
days, it had reached 332,000 views on YouTube, 220,000 views on Instagram, 294,000 views
on Facebook, and 402,000 views on Twitter, with a cumulative count of 1.2 million
views.\autocite{Adam2020} However, the CoVideo's effectiveness to improve knowledge about
preventative COVID-19 behaviours remains unclear. 

Using a randomized controlled trial, we  compared the  effectiveness of the CoVideo
against an attention placebo control (APC) video and no video (control) among online
participants from the United States, the United Kingdom, Germany, Spain, and Mexico. We
measured effectiveness as the difference in mean knowledge about the clinical aspects of
COVID-19 and mean knowledge about behaviours that can prevent COVID-19 spread. The study
results could inform the design of future E-E videos to disseminate evidence-based health
recommendations related to COVID-19 as well as other public health emergencies.   


\subsection*{Methods}

\paragraph{Study design and participants} 

This was a multi-site, parallel group, randomized controlled trial  comparing the
effectiveness of the CoVideo (the intervention arm) against an APC video (the placebo arm)
and no video (the control arm).\autocite{Vandormael2020b} Each trial arm consisted of a
video intervention (the CoVideo, APC video, or no video) and survey questions about
COVID-19 knowledge.  We used an online platform called Prolific Academic
(\url{https://www.prolific.co}) to recruit participants, who selected to enter the study
on a ``first come, first served'' basis. Participants had to be between the age of 18 and
59 years (male, female, or other) and have current residence in the United States, the
United Kingdom, Germany, Spain, or Mexico.  Participants were excluded from the study if
they could not speak English, German, or Spanish. The trial was hosted and deployed on
Gorilla™ (\url{www.gorilla.sc}), which is a cloud platform that provides versatile tools
to undertake online, experimental, and behavioural research.\autocite{Anwyl-Irvine2020}
The study and its outcomes were registered at the German Clinical Trials Register
(www.drks.de) on May 12th, 2020: \#DRKS00021582. Ethical approval was obtained from the
Stanford University IRB on April 12, 2020, \#55820.    

\paragraph{Randomization and masking}

Randomization was at a 1:1:1 ratio for the three arms of the trial.  Because Prolific
Academic handled the interaction between the study investigators and participants, the
participants were completely anonymous to the study investigators. Participants
self-responded to the survey questions and self-submitted their responses anonymously on
the Gorilla platform. The study investigators and those involved in the data analyses and
statistics were blinded to the group (CoVideo, APC, control) allocation.  


\paragraph{Procedures}

Participants began the online study by answering basic demographic questions about their
age, sex, primary language, country of residence, and highest education completed.

Participants were then randomized to the intervention, placebo, or control arms.  The
intervention arm participants received the CoVideo, which is an wordless, animated video
about how the novel coronavirus is spread (airborne, physical contact), and recommends
best practices to prevent or reduce the spread of COVID-19 (staying at home, not
congregating in public spaces, and sanitizing hands/surfaces). The CoVideo also covers the
mass media coverage of the outbreak and the public's response to this media coverage,
which includes a subplot on the stockpiling of essential goods, and the impact thereof on
health-care services and resources (e.g., doctors being unable to access protective
equipment). The CoVideo, which can be viewed at
\url{https://www.youtube.com/watch?v=rAj38E7vrS8}, was designed for universal reach and
optimized for release on social media channels. 


Participants in the placebo arm received the APC. The APC is a wordless, animated video
that has the same duration as the CoVideo.  Its message is about how small choices become
actions, which become habits, which become a way of life
(\url{https://www.youtube.com/watch?v=_HEnohs6yYw}).  We included an APC to account for
possible attention effects elicited by the video medium. APC conditions should mimic the
``inactive'' components of an intervention—the effect of watching the video---while not
containing any of the ``active'' intervention components---the message delivered by the
video.\autocite{Freedland2011} We did not make the assumption that the CoVideo is better
than nothing (i.e., no video). It is possible that the CoVideo could motivate reactance to
the message about preventing COVID-19 spread.\autocite{Dillard2005,Miller2007,
Richards2015} Participants in the control arm received no video. 


Participants answered two types of COVID-19 knowledge questions.  \textit{Clinical
knowledge} of COVID-19, with 10 items to evaluate basic knowledge of the clinical
characteristics of COVID-19.  \textit{Knowledge spread}, with 8 items to evaluate the
knowledge of behaviours to prevent COVID-19 spread.  The 18 knowledge items are shown in
Table \ref{tab:know}.  All items required True/False responses and all participants
received the knowledge items. As a way to prevent online searchers for the answers,
participants were given a count-down of 30 seconds to respond to each knowledge item 

To ensure post-trial access
to treatment,\autocite{Doval2015} participants in the APC and control arm received the
CoVideo after completing the demographic and knowledge questions. 

\paragraph{Outcomes}

The primary outcome was the number of correct responses to the clinical knowledge
questions, the knowledge spread questions, and the combined knowledge questions.


\paragraph{Statistical analysis}

We obtained means and standard deviations of the participants' age, gender, primary
language, country of residence, and education status. For each arm, we calculated the mean
clinical knowledge, knowledge spread, and combined knowledge scores. We defined the
difference in mean scores between the CoVideo and control arms as the Total Effect, the
difference in mean scores between the APC and control arms as the Attention Effect, and
the difference in mean scores between the CoVideo and APC arms as the Treatment Effect.
For participants in the CoVideo and control arms, we used a linear regression model to
quantify the effects of the demographic characteristics on the clinical knowledge,
knowledge spread, and combined knowledge scores.  Statistical analyses were performed with
R software version 4.2.


\paragraph{Role of the funding source}

The funder of the study had no role in study design, data collection, data analysis, data
interpretation, or writing of the report. The corresponding author had full access to all
the data in the study and had final responsibility for the decision to submit for
publication.

\subsection*{Results}


Between \Sexpr{res$dates[1]} and \Sexpr{res$dates[2]}, we recruited \Sexpr{fmt(flow$In)}
participants through the Prolific Academic platform. A total of  \Sexpr{fmt(flow$In -
flow$Start)} participants were randomly assigned to the control (\Sexpr{fmt(flow$CtrlN)})
APC (\Sexpr{fmt(flow$APCN)}), and CoVideo (\Sexpr{fmt(flow$CoVidN)}) arms (Figure
\ref{fig:dataflow}).  Between recruitment and randomization, \Sexpr{flow$Start}
participants were lost.  After randomization to each arm, another \Sexpr{flow$Ctrl}
(control), \Sexpr{flow$APC} (APC), and \Sexpr{flow$Trt} (CoVideo) participants were lost
due to technical reasons.  A total of \Sexpr{fmt(flow$FinalN)} participants completed the
trial and contributed data to the final analysis. 

The majority of participants  reported their residence in the United Kingdom
(\Sexpr{res$ctry["United Kingdom"]}\%) or the United States (\Sexpr{res$ctry["United States"]}\%), and \Sexpr{res$lan["EN"]}\% of participants reported English as their first
language.  The sample was relatively well-educated, with \Sexpr{sum(res$educ[c(3,4)])}\%
having some college education or higher (BA, MA equivalent or PhD).  Table
\ref{tab:tab0} shows the percentage of participants in each arm by age, gender, country of
residence, educational status, and primary language. 


For the primary outcome, the combined knowledge score was higher in the CoVideo arm
relative to the control and APC arms (Figure \ref{fig:knowall}). In the control arm,
\Sexpr{fmt(res_all$means["VideoArmControl"], 2)} out of \Sexpr{an} items
(\Sexpr{fmt(res_all$means["VideoArmControl"]/an*100, 2)}\%) were correctly answered.  With
this high baseline score, the CoVideo could therefore only increase knowledge by a maximum
of \Sexpr{fmt(amax, 2)} points.  Relative to the control arm, the CoVideo increased the
average response by \Sexpr{fmt(adiff, 2)} points (\Sexpr{(res_all$pvals[2, 1])}), which
represents a \Sexpr{fmt(adiff, 2)}/\Sexpr{fmt(amax, 2)} $=$ \Sexpr{fmt(adiff/amax*100, 2)}
percentage point increase in knowledge. The average score for the APC arm was
\Sexpr{fmt(res_all$means["VideoArmPlacebo"],2)}, a correct response rate of
\Sexpr{fmt(res_all$means["VideoArmPlacebo"]/an*100, 2)}\% .  When we removed the attention
effect of the video medium, the CoVideo increased overall knowledge by \Sexpr{fmt(adiff2,
2)} points (\Sexpr{res_all$pvals[2,2]}), which represents a \Sexpr{fmt(adiff2,
2)}/\Sexpr{fmt(amax2, 2)} $=$ \Sexpr{fmt(adiff2/amax2*100, 2)} percentage point increase. 





Clinical knowledge was higher in the CoVideo arm relative to the control and APC arms
(Figure \ref{fig:clinic}). In the control arm, the average items correctly answered was
\Sexpr{fmt(res_know$means["VideoArmControl"], 2)} out of \Sexpr{kn} (a correct response
rate of \Sexpr{fmt(corrects, 1)}\%).  With this high baseline score, the CoVideo could
therefore only increase knowledge by a maximum of \Sexpr{fmt(kmax, 2)} points.  Relative
to the control arm, the CoVideo increased the average response by \Sexpr{fmt(kdiff, 2)}
points (\Sexpr{(res_know$pvals[2, 1])}), which represents a \Sexpr{fmt(kdiff,
2)}/\Sexpr{fmt(kmax, 2)} $=$ \Sexpr{fmt(kdiff/kmax*100, 1)} percentage point increase in
clinical knowledge. The mean knowledge score for the APC arm was
\Sexpr{fmt(res_know$means["VideoArmPlacebo"], 2)}  points. When we removed the attention
effect of the video medium, the CoVideo increased the average response by
\Sexpr{fmt(kdiff2, 2)} (\Sexpr{res_know$pvals[2,2]}), which represents a
\Sexpr{fmt(kdiff2, 2)}/\Sexpr{fmt(kmax2, 2)} $=$ \Sexpr{fmt(kdiff2/kmax2*100, 1)}
percentage point increase in clinical knowledge.  There was no difference in knowledge
spread among the arms (Figure \ref{fig:spread}). In the control arm, the average items
correctly answered was \Sexpr{fmt(res_spr$means["VideoArmControl"], 2)} out of
\Sexpr{kns}, a high correct response rate of \Sexpr{fmt(correctc, 1)}\%.




<<echo=FALSE>>=
getMin <- function(x, Lab) {
  x <- x[x$Label==Lab, grepl("pp", colnames(x))]
  fmt(min(as.numeric(unlist(x))), 1)
}
@


For the clinical knowledge questions, more than \Sexpr{getMin(tabc, "SpreadHealthy")}\%
knew that the coronavirus could be infected by a healthy person even if they looked
healthy; more than \Sexpr{getMin(tabc, "Cough")}\% knew that some people with COVID-19
infection may experience a cough; and more than \Sexpr{getMin(tabc, "TouchFace")}\% knew
that you can catch COVID-19 by touching a contaminated surface and then touching your
face.  The lowest correctly answered item (\Sexpr{getMin(tabc, "CleanSoap")}\%) was
knowing that cleaning surfaces with soap and water is an effective way to kill the
coronavirus.  For the knowledge spread questions, more than \Sexpr{getMin(tabs,
"WashHandSoap")}\% of participants knew that an effective way to prevent COVID-19 spread
is to wash hands frequently with soap and water; and \Sexpr{getMin(tabs,
"NoShakeHands")}\% of participants knew that an effective way to prevent COVID-19 spread
is to avoid shaking hands with other people; and to avoid places that are crowded with
people (like bars, restaurants or performances), respectively. On the lower end,
\Sexpr{getMin(tabs, "RinseSalt")}\%  answered correctly that regularly rinsing your nose
with salt water cannot prevent the spread of COVID-19. 


When compared with the control arm, the CoVideo increased clinical knowledge most in the
45--54 year age group ($\text{Mean Diff.} = \Sexpr{agediff$c4554[1]}$,
\Sexpr{agediff$c4554[3]}) and 55-59 year age group ($\text{Mean
Diff.}=\Sexpr{agediff$c5559[1]}$, \Sexpr{agediff$c5559[3]}). The third largest increase
was in the 18--24 year age group ($\text{Mean Diff.}=\Sexpr{agediff$c1824[1]}$,
\Sexpr{agediff$c1824[3]}). There was no statistically significant difference in knowledge
spread among the control and CoVideo arms by age group. 



Table \ref{tab:modc}  shows the regression results for clinic knowledge items (control arm
only). Older participants (aged 25--54 years) had higher knowledge scores than younger
participants (aged 18-24 years). Women had higher knowledge scores than men and German
speaking residents  the highest knowledge scores, after controlling for the other factors.
Results show that higher education was significantly associated with higher knowledge
scores, with a clear dose response across the education levels.  A higher education level
was also associated with a higher knowledge of COVID-19 spread (Table \ref{tab:mods}).


\subsection*{Discussion}


There is a critical need for public health actors to disseminate scientific information
about the treatment and prevention of COVID-19. To inform the public about the prevention
of COVID-19 spread, we produced a short, animated video that went viral in the first week
of its release on social media.\autocite{Adam2020}  To evaluate the CoVideo's
effectiveness, we recruited \Sexpr{fmt(flow$FinalN)} participants to take part in a
multi-site, parallel group, randomized controlled trial in an online setting.  We asked
participants questions about the basic clinical characteristics of COVID-19
(clinical knowledge) and questions about behaviours to prevent the spread of COVID-19
(knowledge spread).  Our primary aim was to assess if the CoVideo was effective in
improving knowledge about behaviours that can prevent  COVID-19 spread. 


We report that participants in our study had high levels of COVID-19 knowledge.  For
example, \Sexpr{getMin(tabc, "SpreadHealthy")}\% of participants in the control arm knew
that the coronavirus could be infected by a person even if they looked healthy,
\Sexpr{getMin(tabc, "Cough")}\% knew that some people with COVID-19 infection may
experience a cough, and \Sexpr{getMin(tabc, "TouchFace")}\% knew that you can catch
COVID-19 by touching a contaminated surface and then touching your face.  Overall,
participants in the control arm correctly answered \Sexpr{fmt(corrects, 1)}\% of the
clinical knowledge questions, \Sexpr{fmt(correctc, 1)}\% of the knowledge spread
questions, and \Sexpr{fmt(acorrect, 1)}\% of the combined questions.  Given such high
baseline levels, the CoVideo was nevertheless effective at increasing basic knowledge of the
clinical characteristics of COVID-19:   out of the remaining \Sexpr{fmt(100 - corrects,
1)}\% needed to achieve a 100\% correct response rate, the CoVideo increased clinical
knowledge by a further \Sexpr{fmt(kdiff/kmax*100, 1)}\%. After adjusting for attention effects, the
increase in this clinical knowledge was \Sexpr{fmt(kdiff2/kmax2*100, 1)}\%.  

Results show that there was no difference in knowledge about behaviours to prevent COVID-19
spread. There are two likely explanations for this result. The first is that the baseline
knowledge level in the control arm was very high (\Sexpr{fmt(correctc, 1)}\%): possibly,
the CoVideo could not further improve knowledge of behaviours to prevent COVID-spread.  The
second explanation is that it may be easier to improve knowledge about the clinical
features of a disease (such as COVID-19) when compared to improving knowledge about health
behaviours to prevent that disease.
This second explanation has been discussed in the literature with respect to the use of
knowledge to promote health behaviour change, which is often difficult to achieve in
practice.\autocite{Ajzen2011a} Where possible, additional analyses may be needed to
determine which of the two explanations best fits the data. 
 
We report that the COVID-19 knowledge scores differed by several factors. In the control
and CoVideo arms, participants with higher educational status had higher COVID-19
knowledge scores, and women scored higher than men. Of the five countries, Germany had the
highest knowledge scores after adjusting for age, gender, and education level.  Because of
its short, animated format designed for social media release, we expected the CoVideo to
increase knowledge most in the younger age group (18--24 years). Surprisingly, the CoVideo
increased knowledge most  in the older age groups (45-54 and 54-59 years), even after
removing the attention effects of the video format. Given these findings, online E-E
videos about health could be an important means to target older populations who are often
more vulnerable to health issues, as is the case with the  COVID-19
pandemic.\autocite{Zhou2020, Sudharsanan2020}


Our study has several strengths.  We  used state-of-the-art online technology to implement
our randomized controlled trial.\autocite{Vandormael2020b} The Prolific Academic platform
enabled us to rapidly recruit a large number of participants who speak different languages
and live in different countries in Europe, North America, and Latin America.  We  also
hosted our study on the Gorilla platform, which makes it facilitates the design,
implementation, and management of  online trials in behavioural
research.\autocite{Anwyl-Irvine2020} The Gorilla platform provides ready-made mechanisms
for randomization to the trial arms, prevention of repeat or duplicate participants, bot
checks, and questionnaire builders. Further, the Gorilla platform enabled us to implement
design mechanisms such as count-downs (time limits) to prevent respondents from searching for
online answers to the knowledge questions. Together, these tools enabled us to rapidly
recruit a diverse sample of participants while ensuring the rigor of a completely
randomized control design.

Our study results demonstrate the potential of E-E media, such as a short, animated video
format, that can  be rapidly and comprehensively distributed to improve knowledge about an
important public health topic.  We expect that our study will make important contributions
to the E-E literature.  These lessons can improve the design of E-E videos to disseminate
public health information for future pandemics.  Our results will also guide future E-E
strategies to support the long-term COVID-19 response as countries begin to ease lock-down
restrictions.


\paragraph{Contributors}

AV wrote the paper, MA, MG, JG, and TB provided comments and feedback. MA designed the
CoVideo. AV and TB designed the trial. All authors contributed to the questionnaire
development.


\paragraph{Declaration of interests}
We declare no competing interests. 

\paragraph{Acknowledgments}
This study is funded by the Alexander von Humboldt University Professor Prize, awarded to
TB.

