% !Rnw root = master.Rnw
%! TEX root = master.tex
\Sexpr{knitr::set_parent('master.Rnw')}



\subsection*{Introduction}

A large amount of published health information about the novel coronavirus (COVID-19) has
been disseminated by the traditional mass media since the outbreak of the
pandemic.\citep{Cinelli2020,Kouzy2020,Mian2020a} However, it is not clear if this
information has improved knowledge of preventive COVID-19 behaviours. By preventive
behaviours, we mean the public's adoption of practices such as social distancing and hand
sanitation (among others) that can reduce the spread of COVID-19. 

Arguably, one possible limitation of mainstream mass media is that it is perceived
as politicized and culturally localized, thus limiting the persuasiveness of health
messages about COVID-19.\citep{Garfin2020a, Garrett2020} It is also likely that
traditional mass media channels (e.g., local or national television networks) have missed
key segments of the population, such as young people (18--35 years) who are
disproportionately more likely to transmit the virus.\citep{Dowd2020, Harris2020,
Zhao2020} An effective public health response could benefit from the rapid distribution of
entertainment-education (E-E) approaches through social media channels to a diverse and
global audience.\citep{Hahn2020, Block2020} 

We have designed a short, wordless, and animated E-E video to improve knowledge of
preventive COVID-19 behaviours.  The E-E video was released on Stanford Medicine's YouTube
channel on March 21, 2020 and reached 332,000 views on YouTube, 220,000 views on
Instagram, 294,000 views on Facebook, and 402,000 views on Twitter, with a cumulative
count of 1.2 million views within 10 days.\citep{Adam2020} Using a randomized
controlled trial (RCT), we evaluate the E-E video's effectiveness among online participants from
the United States of America (USA), Mexico, the United Kingdom (UK), Germany, and Spain. 


% Our study results will inform the design of future E-E videos to disseminate
% evidence-based health recommendations related to COVID-19 as well as other public health
% emergencies.   


\subsection*{Methods}

\paragraph{Study design and participants} 

This was a multi-site, parallel group, RCT comparing the effectiveness of the E-E video
against an attention placebo control (APC) video and do-nothing.\citep{Vandormael2020b} We
used an online platform called Prolific Academic (\url{https://www.prolific.co}) to enroll
participants on a ``first come, first served'' basis. Participant eligibility included
being  18 to 59 years of age (male, female, or other), having residence in the USA, the UK,
Germany, Spain, or Mexico, and having proficiency in English, German, or Spanish. The
trial was hosted and deployed on Gorilla (\url{www.gorilla.sc}), which is a cloud platform
that provides versatile tools to undertake online, experimental, and behavioural
research.\citep{Anwyl-Irvine2020} The study and its outcomes were registered at the German
Clinical Trials Register (www.drks.de) on May 12th, 2020: \#DRKS00021582. Ethical approval
was obtained from the Stanford University IRB on April 12, 2020, \#55820.    

\paragraph{Randomization and masking}

Randomization was at a 1:1:1 ratio for the three arms of the trial.  Because Prolific
Academic handled the interaction between the study investigators and participants, the
participants were completely anonymous to the study investigators. Participants
self-responded to the survey questions and self-submitted their responses anonymously on
the Gorilla platform. The study investigators were blinded to the group
allocation.\citep{Vandormael2020b} 


\paragraph{Procedures}

Participants began the online study on the Gorilla platform by answering basic demographic
questions about their age, sex, primary language, country of residence, and highest
education completed.

Participants were  then randomly assigned by Gorilla to the E-E video, APC, or do-nothing.
The E-E video describes how the novel coronavirus is spread (airborne, physical contact),
and recommends best practices to prevent or reduce the spread of COVID-19 (staying at
home, not congregating in public spaces, and sanitizing hands and surfaces). It also
covers the mass media coverage of the epidemic and a subplot about the stockpiling of
essential goods (\url{https://www.youtube.com/watch?v=rAj38E7vrS8}).\citep{Adam2020}


The APC is also a wordless, animated video with the same duration as the E-E video.  Its
content describes how small choices become actions, which become habits, which become a
way of life (\url{https://www.youtube.com/watch?v=_HEnohs6yYw}).  We included an APC to
account for possible attention effects elicited by the video medium. APC conditions should
mimic the ``inactive'' components of an intervention—the effect of watching the
video---while not containing any of the ``active'' intervention components---the content
delivered by the video.\citep{Freedland2011} We did not make the assumption that the
E-E video is better than nothing (i.e., no video). It is possible that the E-E video could
motivate reactance to our COVID-19 prevention message.\citep{Dillard2005,Miller2007,
Richards2015} 


Participants answered 18 questions on preventive COVID-19 behaviors. All items required
True/False responses and all participants received the knowledge items. To prevent online
searching for answers, participants had a 30 second count-down to respond to each
item. To ensure post-trial access to treatment,\citep{Doval2015} participants in the
APC and do-nothing arm could choose to watch the E-E video at the end of the
study. 


\paragraph{Statistical analysis}


The primary outcome was the average number of correct answers to the 18 knowledge
questions.  For each participant, we created an overall knowledge score (minimum $=$ 0,
maximum $=$ 18) by adding the correctly answered items. We used an ordinary least squares
(OLS) regression to estimate the mean knowledge score by trial arm and to estimate the
difference in knowledge scores between trial arms. We defined the difference in mean
knowledge scores between the E-E video and do-nothing arms as the total effect, the
difference between the APC and do-nothing arms as the attention effect, and the difference
between the E-E video and APC arms as the content effect.  We also summarized the
participant characteristics by obtaining means and standard deviations of age, gender,
primary language, country of residence, and education status.  Statistical analyses were
performed with R software version 4.2.


\paragraph{Role of the funding source}

The funder of the study had no role in study design, data collection, data analysis, data
interpretation, or writing of the report. The corresponding author had full access to all
the data in the study and had final responsibility for the decision to submit for
publication.

\subsection*{Results}


Between \Sexpr{res$dates[1]} and \Sexpr{res$dates[2]}, we enrolled \Sexpr{fmt(flow$In)}
participants through the Prolific Academic platform. A total of  \Sexpr{fmt(flow$In -
flow$Start)} participants were randomly assigned to the E-E video
(\Sexpr{fmt(flow$CoVidN)}), APC (\Sexpr{fmt(flow$APCN)}), and do-nothing
(\Sexpr{fmt(flow$CtrlN)}) arms (Figure \ref{fig:dataflow}).  Between recruitment and
randomization, \Sexpr{flow$Start} participants were lost and  after randomization another
\Sexpr{flow$Ctrl} (do-nothing), \Sexpr{flow$APC} (APC), and \Sexpr{flow$Trt} (E-E video)
were lost for unknown reasons (possibly due  technical reasons such as a lost
internet connection, issues with linking to the video host, YouTube, server complications,
etc).  A total of \Sexpr{fmt(flow$FinalN)} participants completed the trial and
contributed data to the final analysis. 

The majority of participants  reported their residence in the UK
(\Sexpr{res$ctry["United Kingdom"]}\%) or the USA
(\Sexpr{res$ctry["United States"]}\%), and \Sexpr{res$lan["EN"]}\% of participants reported English as their first
language.  The sample was relatively well-educated, with \Sexpr{sum(res$educ[c(3,4)])}\%
having some college education or higher (BA, MA equivalent or PhD).  Table \ref{tab:tab0}
shows the percentage of participants in each arm by age, gender, country of residence,
educational status, and primary language. 

The E-E video significantly increased knowledge of preventive COVID-19 behaviors when
compared with the APC and do-nothing arms (Figure \ref{fig:knowall}). In the do-nothing
arm, participants correctly answered \Sexpr{fmt(know_res$means["VideoArmControl"], 2)}
(95\% confidence interval (CI): 
\Sexpr{fmt(know_res$cis["VideoArmControl", "2.5 %"], 2)} --
\Sexpr{fmt(know_res$cis["VideoArmControl", "97.5 %"], 2)}}) 
out of the \Sexpr{an} items, which is a
\Sexpr{fmt(know_res$means["VideoArmControl"]/an*100, 2)}\% correct response rate.  With
this high baseline score, the E-E video could therefore only increase knowledge by a
maximum of \Sexpr{fmt(amax, 2)} points.  Relative to the do-nothing arm, the E-E video
increased knowledge by \Sexpr{know_res$totdiff$diff} points
(Mean $=$ \Sexpr{fmt(know_res$means["VideoArmTreatment"], 2)}, 
95\% CI: \Sexpr{fmt(know_res$cis["VideoArmTreatment", "2.5 %"], 2)} --
\Sexpr{fmt(know_res$cis["VideoArmTreatment", "97.5 %"], 2)}}; 
\Sexpr{(know_res$totdiff$pval)}), which represents an increase of
\Sexpr{fmt(know_res$totdiff$diff, 2)}/\Sexpr{fmt(amax, 2)} $=$
\Sexpr{fmt(as.numeric(know_res$totdiff$diff)/amax*100, 2)}\%. The average score for the
APC arm was \Sexpr{fmt(know_res$means["VideoArmPlacebo"],2)} 
(95\% CI: \Sexpr{fmt(know_res$cis["VideoArmPlacebo", "2.5 %"], 2)},
\Sexpr{fmt(know_res$cis["VideoArmPlacebo", "97.5 %"], 2)}}),
 a correct response rate of
\Sexpr{fmt(know_res$means["VideoArmPlacebo"]/an*100, 2)}\%.  When we removed the attention
effect of the video format, the E-E video increased overall knowledge by
\Sexpr{know_res$contdiff$diff} points (\Sexpr{know_res$contdiff$pval}), which represents
an increase of \Sexpr{know_res$contdiff$diff}/\Sexpr{fmt(amax2, 2)} $=$
\Sexpr{fmt(as.numeric(know_res$contdiff$diff)/amax2*100, 2)}\%.

<<echo=FALSE>>=
ctl <- arrange(ctl, desc(est))
@



Figure \ref{fig:forest} shows the proportion of correct responses to each of the 18
knowledge items (see also Table \ref{tab:tabk}).  The highest correctly answered item was
\Sexpr{fmt(ctl[1, 2]*100, 1)}\%  (``An effective way to prevent COVID-19 spread is to wash
your hands frequently with soap and water''), with most items having a
$>90\%$ correct response rate. 


<<echo=FALSE>>=
getMin <- function(x, Lab) {
  x <- x[x$Label==Lab, grepl("pp", colnames(x))]
  fmt(min(as.numeric(unlist(x))), 1)
}
@

As post-access to treatment, participants in the APC and do-nothing arms ($n =
\Sexpr{fmt(sum(table(dat_all$VideoArm)[-3]))}$) were given the choice to watch the E-E
video. Of these participants, \Sexpr{fmt(leftwatch)} received the E-E video,
\Sexpr{round(watched*100, 1)}\% chose to view the E-E video, and
\Sexpr{round(less150*100, 1)}\% viewed the E-E video to the end.




\subsection*{Discussion}

% There is a critical need for public health actors to disseminate scientific information
% about the prevention of COVID-19. 

We have designed a short, animated E-E video to disseminate information about
preventive COVID-19 behaviors.\citep{Adam2020, Vandormael2020b} To evaluate the E-E
video's effectiveness, we enrolled \Sexpr{fmt(flow$In)} online participants from the USA,
Mexico, UK, Spain, and Germany into a randomized controlled trial.  The primary outcome of
the study was to compare differences in COVID-19 prevention knowledge between the E-E
video, an APC video, and a do-nothing trial arms. 




Our results show that the E-E video boosted knowledge of preventive COVID-19 behaviors.
Baseline knowledge in the do-nothing arm was already high, with an average
\Sexpr{fmt(know_res$means["VideoArmControl"], 1)} of the 18 questions correctly answered
(\Sexpr{fmt(know_res$means["VideoArmControl"]/an*100, 1)}\%).  Therefore, another
\Sexpr{fmt(amax, 2)} points were needed to achieve a 100\% score. The E-E video increased
the baseline score by \Sexpr{know_res$totdiff$diff} points, which represents a knowledge
increase of \Sexpr{fmt(as.numeric(know_res$totdiff$diff)/amax*100, 1)}\%.  When we
adjusted for the attention effects of the video format, the increase in knowledge was
\Sexpr{fmt(as.numeric(know_res$contdiff$diff)/amax2*100, 1)}\%.  These gains in knowledge,
even with already high baseline levels, demonstrate the effectiveness of our E-E video to
improve knowledge of preventive COVID-19 behaviors. 


Overall, participants in the do-nothing arm correctly answered \Sexpr{fmt(acorrect, 1)}\%
of the knowledge questions.  The highest correctly answered item was \Sexpr{fmt(ctl[1,
2]*100, 1)}\%  (``An effective way to prevent COVID-19 spread is to wash your hands
frequently with soap and water''), with most of the remaining items having a $>90\%$
correct response rate.  These high scores could reflect the relatively well educated
status of our online sample, with \Sexpr{sum(res$educ[c(3,4)])}\% having some college
education or higher (BA, MA, PhD equivalent).  It is possible that our sample was more
educated than the general populations of the USA, the UK, Germany, Spain, and Mexico.
Nevertheless, our study shows a similar educational composition to a recent study on
COVID-19 knowledge in the USA and UK, where 76\% of the online sample had some college
education or higher.\citep{Geldsetzer2020}




Our study has several strengths.  We  used state-of-the-art online technology to implement
our randomized controlled trial.\citep{Vandormael2020b} Through the Prolific Academic
platform, we rapidly  recruited a large number of participants who speak different
languages and live in different countries in Europe, North America, and Latin America.  We
also hosted our study on the Gorilla platform, which provides services for the design,
implementation, and management of  online trials in behavioural
research.\citep{Anwyl-Irvine2020} Gorilla has ready-made tools for randomization to the
trial arms, blinding, prevention of repeat or duplicate participants, bot checks,
questionnaire builders, and count-downs (time limits), which we used to prevent
respondents from searching for online answers to the knowledge questions. Together, these
tools enabled us to rapidly recruit online participants and ensure the rigour  of a
completely randomized controlled design.


As an additional strength of this study, we were able to measure participant engagement
with the E-E video intervention.  To ensure post-access to treatment, we offered
participants in the APC and do-nothing arms the option to watch the E-E video.  We used Gorilla
tools to  record whether participants' clicked ``End the study'' or ``Watch the video''
and also recorded the time spent watching the E-E video.  Our preliminary results show a
relatively high engagement with the E-E video: of the \Sexpr{round(watched*100)}\%
participants that chose to watch, \Sexpr{round(less150*100, 0)}\% watched to the end.
This engagement is interesting given that respondents already knew most of the COVID-19
facts featured in the E-E video. It is plausible that the APC and do-nothing arm participants
believed they could benefit from watching the E-E video and gain further COVID-19 information.
To this extent, the E-E video may have increased the participants' subjective probability
that their current COVID-19 knowledge was correct.  Finally, it is possible that the
E-E video elicited some form of emotional engagement in  participants, such as giving them
a sense of hope or reassurance. Further E-E studies are needed to measure the
potential for using emotional engagement to sustain attention to health messages.


Our study results demonstrate the potential of E-E media, such as a short, animated video
format that can  be rapidly and comprehensively distributed to improve knowledge about an
important public health topic.  We expect that our study will make important contributions
to the E-E literature.  These lessons can improve the design of E-E videos to disseminate
public health information for future pandemics.  Our results will also guide future E-E
strategies to support the long-term COVID-19 response as countries begin to ease or renew
lock-down restrictions.


\paragraph{Contributors}

AV wrote the paper and undertook the statistical analysis. TB, MA, MG, and JG provided
comments and feedback. MA designed, produced, and created the E-E video. TB and AV designed
the trial. AV, TB, MA, and MG contributed to the questionnaire development.


\paragraph{Declaration of interests}
We declare no competing interests. 

\paragraph{Acknowledgments}
TB is funded by the Alexander von Humboldt University Professor Prize.

