%! TEX root = master.tex
\documentclass[11pt]{article}
\usepackage{epsfig,epic,eepic,units}
\usepackage[T1]{fontenc}
\usepackage{mathrsfs}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{mdwlist}
\usepackage{paralist}
\usepackage{enumitem}
\usepackage{booktabs}
% \usepackage{verbatim}
\usepackage{graphicx}
\usepackage{array}
% \usepackage[flushleft]{threeparttable}
\usepackage{titlesec}
\usepackage[font=small]{caption}
\usepackage[footskip=0.3in,margin=1in]{geometry} 
\usepackage[draft]{hyperref}
\usepackage[numbers,sort&compress,super]{natbib}
% \usepackage{xcolor}
% \usepackage[modulo]{lineno}
% \linenumbers


% \usepackage[natbib=true, style=nature, isbn=false, doi=false, url=false]{biblatex}
% \addbibresource{library.bib}

\graphicspath{{C:/Users/alainv/Seafile/Heidelberg/Projects/CoVideo/Paper_1/output/}
{C:/Users/alain.vandormael/Seafile/Heidelberg/Projects/CoVideo/Paper_1/output/}}
 
\titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
  
\titleformat{\paragraph}{\normalfont\slshape}{\theparagraph}{1em}{}
\titlespacing*{\paragraph}{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt}

\setlength{\parskip}{0.5\baselineskip plus 2pt minus 2pt}
\setlength{\parindent}{0pt}% 
\linespread{1.2}
\pagenumbering{arabic}


<<echo=FALSE>>=
library(covideo)
library(xtable)
library(tidyverse)
knitr::opts_chunk$set(
  fig.width=5, fig.heigh=5,
  tidy.opts=list(blank = FALSE, width.cutoff = 60), 
  tidy = FALSE,
  out.width=' 9cm', out.height=' 9cm')
@


<<echo=FALSE>>=
home <- file.path(Sys.getenv("HOME"), "Seafile\\Heidelberg\\Projects\\CoVideo\\Paper_1")
output <- file.path(home, "output")
dat_all <- load_covideo()
load(file.path(output, "Results.RData"), envir=.GlobalEnv)
load(file.path(output, "ResultsFigs.RData"), envir=.GlobalEnv)
@

<<echo=FALSE>>=
an <- length(c(sstate(), cstate()))
amax <- an - know_res$means["VideoArmControl"]
amax2 <- an - know_res$means["VideoArmPlacebo"]
acorrect <- know_res$means["VideoArmControl"]/an*100
@

<<echo=FALSE>>=
fmt <- function(x, d=0) formatC(x, format="f", digits=d, big.mark=",")
fmtCI <- function(x) {
  dd <- behav[rownames(behav) %in% x, ]
  ci <- paste0("95\\% CI: ", dd["LB"], "--", dd["UB"], "\\%")
  mn <- paste0(dd["Est"], "\\%")
  return(list(both = paste0(mn, ", ", ci), mn=mn, ci=ci))
}
@

<<echo=FALSE>>=
# % by arms
arm_n <- tapply(dat_all$ID, dat_all$VideoArm, function(x) length(unique(x)))
@


\title{The effectiveness of an entertainment-education video on COVID-19 prevention
knowledge: an online randomized controlled trial of \Sexpr{fmt(flow$In)} adults in the
USA, Mexico, UK, Germany, and Spain.  }
\date{\vspace{-8ex}}


\begin{document}

\maketitle

\begin{center}
{Alain Vandormael, PhD}$^{1*}$,
{Maya Adam, PhD}$^2$,
{Merlin Greuel, MSc}$^1$, \\
{Jennifer Gates, BSc}$^3$
\& {Till B\"arnighausen, PhD}$^{1,4,5}$
\end{center}

{\footnotesize
$^{1}${Heidelberg Institute of Global Health, University of Heidelberg, Heidelberg, Germany} \\
$^{2}${Department of Pediatrics, Stanford University School of Medicine, Stanford, CA, USA} \\
$^{3}${Icahn School of Medicine, Mount Sinai, New York, USA} \\
$^{4}${Africa Health Research Institute (AHRI), Durban, South Africa.} \\
$^{5}${Department of Global Health and Population, Harvard T.H. Chan School of Public Health, Boston, USA} \\
$^{*}${Corresponding author: alain.vandormael@uni-heidelberg.de}
}


\textbf{Contact Information} \\
Dr. Alain Vandormael \\
130.3 Im Neuenheimer Feld, \\
Heidelberg Institute of Global Health, \\
University of Heidelberg, \\
69120, Germany, \\
email: alain.vandormael@uni-heidelberg.de \\
Tel. number: +46 163 481 3452

\medskip
Word count < 3,000 


\clearpage

<<abstract, child='abstract.Rnw', eval=TRUE>>=
@

<<results, child='main.Rnw', eval=TRUE>>=
@

<<tabs, child='tables.Rnw', eval=TRUE>>=
@

<<tabs, child='figures.Rnw', eval=TRUE>>=
@

% \subsection*{References}
\sloppy

% \printbibliography[noheading]


\bibliography{library}
\bibliographystyle{unsrtnat} % style of bibliography


<<tabs, child='supp.Rnw', eval=FALSE>>=
@




\end{document}
