%! TEX root = master.tex
\documentclass[11pt]{article}
\usepackage{epsfig,epic,eepic,units}
\usepackage[T1]{fontenc}
\usepackage{mathrsfs}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{mdwlist}
\usepackage{paralist}
\usepackage{enumitem}
\usepackage{booktabs}
\usepackage{verbatim}
\usepackage{graphicx}
\usepackage{array}
\usepackage[flushleft]{threeparttable}
\usepackage{authblk}
\usepackage{titlesec}
\usepackage[font=small]{caption}
\usepackage[footskip=0.3in,margin=1in]{geometry} 
\usepackage{xcolor}
\usepackage[modulo]{lineno}
\linenumbers

\usepackage[style=nature, isbn=false, doi=false, url=false]{biblatex}
\addbibresource{library.bib}

\graphicspath{{C:/Users/alainv/Seafile/Heidelberg/Projects/CoVideo/drafts/output/}
{C:/Users/alain.vandormael/Seafile/Heidelberg/Projects/CoVideo/drafts/output/}}
 
\titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
  
\titleformat{\paragraph}{\normalfont\slshape}{\theparagraph}{1em}{}
\titlespacing*{\paragraph}{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt}

\setlength{\parskip}{0.5\baselineskip plus 2pt minus 2pt}
\setlength{\parindent}{0pt}% 
\linespread{1.2}
\pagenumbering{arabic}



\title{Going viral---an entertainment-education response to COVID-19: a parallel group, randomized controlled trial}

\renewcommand*{\Affilfont}{\footnotesize\normalfont}
\date{\vspace{-5ex}}
\author[1, 2*]{Alain Vandormael}
\author[3]{Maya Adam}
\author[1]{Merlin Greuel}
\author[4]{Jennifer Gates}
\author[1,5,6]{Till B\"arnighausen}
\affil[1]{Heidelberg Institute of Global Health, University of Heidelberg, Heidelberg, Germany}
\affil[2]{KwaZulu-Natal Research and Innovation Sequencing Platform, University of KwaZulu-Natal, Durban, South Africa}
\affil[3]{Department of Pediatrics, Stanford University School of Medicine, Stanford, CA, USA}
\affil[4]{Icahn School of Medicine, Mount Sinai, New York, USA}
\affil[5]{Africa Health Research Institute (AHRI), Durban, South Africa.}
\affil[6]{Department of Global Health and Population, Harvard T.H. Chan School of Public Health, Boston, USA}
\affil[*]{Corresponding author: alain.vandormael@uni-heidelberg.de}



<<echo=FALSE>>=
library(xtable)
library(tidyverse)
knitr::opts_chunk$set(
  fig.width=5, fig.heigh=5,
  tidy.opts=list(blank = FALSE, width.cutoff = 60), 
  tidy = FALSE,
  out.width=' 9cm', out.height=' 9cm')
@


<<echo=FALSE>>=
home <- file.path(Sys.getenv("HOME"), "Seafile\\Heidelberg\\Projects\\CoVideo")
output <- file.path(home, "drafts/output")
dat_all <- readRDS(file.path(home, "Data/Derived/dat_all.Rda"))
load(file.path(output, "Results.RData"), envir=.GlobalEnv)
@



\begin{document}

\maketitle






<<results, child='main.Rnw', eval=TRUE>>=
@

<<tabs, child='tables.Rnw', eval=TRUE>>=
@

<<tabs, child='figures.Rnw', eval=TRUE>>=
@

\subsection*{References}
\sloppy

\printbibliography[heading=none]

<<tabs, child='supp.Rnw', eval=TRUE>>=
@




\end{document}
