%! TEX root = master.tex
\documentclass[11pt]{article}
\usepackage{epsfig,epic,eepic,units}
\usepackage[T1]{fontenc}
\usepackage{mathrsfs}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{mdwlist}
\usepackage{paralist}
\usepackage{enumitem}
\usepackage{booktabs}
\usepackage{verbatim}
\usepackage{graphicx}
\usepackage{array}
\usepackage[flushleft]{threeparttable}
\usepackage{authblk}
\usepackage{titlesec}
\usepackage[font=small]{caption}
\usepackage[footskip=0.3in,margin=1in]{geometry} 
\usepackage{xcolor}
\usepackage[modulo]{lineno}
\linenumbers

\usepackage[style=nature, isbn=false, doi=false, url=false]{biblatex}
\addbibresource{library.bib}

\graphicspath{{C:/Users/alainv/Seafile/Heidelberg/Projects/CoVideo/Paper_1/output/}
{C:/Users/alain.vandormael/Seafile/Heidelberg/Projects/CoVideo/Paper_1/output/}}
 
\titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
  
\titleformat{\paragraph}{\normalfont\slshape}{\theparagraph}{1em}{}
\titlespacing*{\paragraph}{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt}

\setlength{\parskip}{0.5\baselineskip plus 2pt minus 2pt}
\setlength{\parindent}{0pt}% 
\linespread{1.2}
\pagenumbering{arabic}



\renewcommand*{\Affilfont}{\footnotesize\normalfont}
\date{\vspace{-5ex}}
\author[1*]{Alain Vandormael}
\author[2]{Maya Adam}
\author[1]{Merlin Greuel}
\author[3]{Jennifer Gates}
\author[1,4,5]{Till B\"arnighausen}
\affil[1]{Heidelberg Institute of Global Health, University of Heidelberg, Heidelberg, Germany}
\affil[2]{Department of Pediatrics, Stanford University School of Medicine, Stanford, CA, USA}
\affil[3]{Icahn School of Medicine, Mount Sinai, New York, USA}
\affil[4]{Africa Health Research Institute (AHRI), Durban, South Africa.}
\affil[5]{Department of Global Health and Population, Harvard T.H. Chan School of Public Health, Boston, USA}
\affil[*]{Corresponding author: alain.vandormael@uni-heidelberg.de}



<<echo=FALSE>>=
library(covideo)
library(xtable)
library(tidyverse)
knitr::opts_chunk$set(
  fig.width=5, fig.heigh=5,
  tidy.opts=list(blank = FALSE, width.cutoff = 60), 
  tidy = FALSE,
  out.width=' 9cm', out.height=' 9cm')
@


<<echo=FALSE>>=
home <- file.path(Sys.getenv("HOME"), "Seafile\\Heidelberg\\Projects\\CoVideo\\Paper_1")
output <- file.path(home, "output")
dat_all <- load_covideo()
load(file.path(output, "Results.RData"), envir=.GlobalEnv)
load(file.path(output, "ResultsFigs.RData"), envir=.GlobalEnv)
@

<<echo=FALSE>>=
fmt <- function(x, d=0) formatC(x, format="f", digits=d, big.mark=",")
@

<<echo=FALSE>>=
adiff <- know_res$means["VideoArmTreatment"] - know_res$means['VideoArmControl']
adiff2 <- know_res$means["VideoArmTreatment"] - know_res$means['VideoArmPlacebo']
an <- length(c(sstate(), cstate()))
amax <- an - know_res$means["VideoArmControl"]
amax2 <- an - know_res$means["VideoArmPlacebo"]
acorrect <- know_res$means["VideoArmControl"]/an*100
@

<<echo=FALSE>>=
kdiff <- know_res$means["VideoArmTreatment"] - know_res$means['VideoArmControl']
kdiff2 <- know_res$means["VideoArmTreatment"] - know_res$means['VideoArmPlacebo']
kn <- length(cstate())
kmax <- kn - know_res$means["VideoArmControl"]
kmax2 <- kn - know_res$means["VideoArmPlacebo"]
corrects <- know_res$means["VideoArmControl"]/kn*100
@


<<echo=FALSE, eval=FALSE>>=
kns <- length(sstate())
kmaxc <- kn - res_spr$means["VideoArmControl"]
correctc <- res_spr$means["VideoArmControl"]/kns*100
@

<<echo=FALSE>>=
fmtCI <- function(x) {
  dd <- behav[rownames(behav) %in% x, ]
  ci <- paste0("95\\% CI: ", dd["LB"], "--", dd["UB"], "\\%")
  mn <- paste0(dd["Est"], "\\%")
  return(list(both = paste0(mn, ", ", ci), mn=mn, ci=ci))
}
@

<<echo=FALSE>>=
# % by arms
arm_n <- tapply(dat_all$ID, dat_all$VideoArm, function(x) length(unique(x)))
@


\title{The effectiveness of an entertainment-education video on COVID-19 prevention
knowledge: an online randomized controlled trial of \Sexpr{fmt(flow$In)} adults in the
USA, Mexico, UK, Germany, and Spain.  }



\begin{document}

\maketitle


\clearpage


<<abstract, child='abstract.Rnw', eval=TRUE>>=
@

<<results, child='main.Rnw', eval=TRUE>>=
@

<<tabs, child='tables.Rnw', eval=TRUE>>=
@

<<tabs, child='figures.Rnw', eval=TRUE>>=
@

\subsection*{References}
\sloppy

\printbibliography[heading=none]

<<tabs, child='supp.Rnw', eval=TRUE>>=
@




\end{document}
