% For LaTeX-Box: root = master.tex
% !Rnw root = master.Rnw
\Sexpr{knitr::set_parent('master.Rnw')}

\clearpage

\subsection*{Supplementary Tables}
\label{sub:SupTables}
\setcounter{table}{0}
\renewcommand{\thetable}{S\arabic{table}}





\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Shows the 18 COVID-19 knowledge items; all responses  required True/False responses. } 

\label{tab:know}
\footnotesize
\begin{tabular}{p{14cm}}
\toprule
<<echo=FALSE, results='asis'>>=
cknow = data.frame(sapply(cstate(), function(x) x[[1]]))
print(xtable(cknow),
  include.colnames=FALSE,
  include.rownames=FALSE,
  hline.after=NULL,
  only.contents=TRUE)
@
<<echo=FALSE, results='asis'>>=
sknow = data.frame(sapply(sstate(), function(x) x[[1]]))
print(xtable(sknow),
  include.colnames=FALSE,
  include.rownames=FALSE,
  hline.after=NULL,
  only.contents=TRUE)
@


\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}

