% For LaTeX-Box: root = master.tex
% !Rnw root = master.Rnw
\Sexpr{knitr::set_parent('master.Rnw')}

\clearpage

\subsection*{Supplementary Tables}
\label{sub:SupTables}
\setcounter{table}{0}
\renewcommand{\thetable}{S\arabic{table}}


\renewcommand{\arraystretch}{1.0}% Tighter
\setlength{\tabcolsep}{5pt}

% \begin{table}[h!]
% \centering
\begin{threeparttable}

\caption{Correct response rates for clinical knowledge of COVID-19 and knowledge of
behaviors to prevent  COVID-19 spread by CoVideo, Attention
Placebo Control (APC), and Control arms  ($N = $ \Sexpr{fmt(flow$FinalN)}).}

\label{tab:tabk}
\footnotesize

\begin{tabular}{p{7.0cm} *{9}{C{0.75cm}}}
  \toprule
  & \multicolumn{3}{c}{\textbf{Control}} &
  \multicolumn{3}{c}{\textbf{APC}}  &
  \multicolumn{3}{c}{\textbf{CoVideo}} \\ 
  \cmidrule(r){2-4}  \cmidrule(r){5-7} \cmidrule(r){8-10} 
  & {\textbf{False}} &
   {\textbf{True}} &
   {\textbf{\%\tnote{$*$}}} 
  & {\textbf{False}} &
   {\textbf{True}} &
   {\textbf{\%\tnote{$*$}}} 
  & {\textbf{False}} &
   {\textbf{True}} &
   {\textbf{\%\tnote{$*$}}} \\
  \midrule
\multicolumn{2}{l}{\textit{Clinical knowledge of COVID-19 spread}} \\
<<echo=FALSE, results='asis'>>=
print(xtable(tabc[, 1:9]),
      include.rownames=TRUE,
      include.colnames=FALSE,
      sanitize.rownames.function=function(x) x,
      hline.after=NULL,
      only.contents=TRUE)
@
\hline 
\multicolumn{2}{l}{\textit{Knowledge of preventing COVID-19 spread}} \\
<<echo=FALSE, results='asis'>>=
print(xtable(tabs[, c(1:9)]),
      include.rownames=TRUE,
      include.colnames=FALSE,
      sanitize.rownames.function=function(x) x,
      hline.after=NULL,
      only.contents=TRUE)
@
\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize  * Represents the percentage of items correctly answered.
\end{tablenotes}
\end{threeparttable}
% \end{table}



