% For LaTeX-Box: root = master.tex
% !Rnw root = master.Rnw
\Sexpr{knitr::set_parent('master.Rnw')}


\subsection*{Figures}
\label{sub:Figures}

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.6]{DataFlow1.png}
\caption{Trial design.}
\label{fig:dataflow}
\end{figure} 


\clearpage

\renewcommand{\note}{%
Mean differences between the CoVideo, Attention Placebo Control (APC), and Control (no
video) are reported with p-values ($N= $\Sexpr{fmt(flow$FinalN)}).  Tot.~Diff.~represents
the total difference in means between the CoVideo and the Control; Att.~Diff.~represents
the attention difference in means between the APC and Control; and Trt.~Diff.~represents
the treatment difference in means between the CoVideo and the APC.  }

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.80]{KnowledgeAll.png}

\caption{Mean score for the combined COVID-19 knowledge questions (18 items) by trial arm.   \note    }

\label{fig:knowall}
\end{figure} 


\begin{figure}[!ht]
\centering
\includegraphics[scale=0.75]{ClinicTotal.png}

\caption{Mean scores for the clinical knowledge of COVID-19 questions (10 items) by trial arm. \note}

\label{fig:clinic}
\end{figure} 

\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.75]{SpreadTotal.png}

\caption{Mean score for the knowledge spread of COVID-19 questions (8 items).  \note}

\label{fig:spread}
\end{figure} 

\clearpage



\begin{figure}[!ht]
\centering
\includegraphics[scale=0.73]{BehavIntent.png}

\caption{Shows the percentage of participants in the Control arm that agreed with
statements about COVID-19 behaviors ($n = $ \Sexpr{fmt(flow$CtrlN - flow$Ctrl)}).  Results
were obtained from  list randomization expriment, which was used to remove social
desirability bias.}

\label{fig:behav}
\end{figure} 


\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.73]{List_1.png}

\caption{Shows the proportion of participants by age and gender that agreed with
statements about COVID-19 behaviors. The proportion represents the difference between the mean
scores in the control list and treatment list of the Control arm ($n = $ \Sexpr{fmt(flow$CtrlN -
flow$Ctrl)}).}

\label{fig:soc}
\end{figure} 

\clearpage

% \begin{figure}[!ht]
% \centering
% \includegraphics[scale=0.73]{BehavDiffs.png}
% \caption{Test}
% \end{figure} 
% \clearpage
