% For LaTeX-Box: root = master.tex
% !Rnw root = master.Rnw
\Sexpr{knitr::set_parent('master.Rnw')}

\subsection*{Supplementary Figures}
\label{sub:SupFigures}
\setcounter{figure}{0}
\renewcommand{\thefigure}{S\arabic{figure}}

% \begin{figure}[h]
% \begin{center}
% \captionsetup{width=0.9\linewidth}

% \caption{Compares the basic demographic characteristics of repeat-testers that entered the
%   HIV cohort (labeled as HIV cohort) with eligible HIV-negative participants that did not
%   enter the HIV cohort (labeled as HIV-negatives).  The comparison between both groups is
%   for the percentage that were women, the mean age (in years) by sex, and the mean number
% of in-migration and out-migration events irrespective of serostatus. The figure show that
% the basic demographic characteristics  not markedly differ between the two groups. }

% \label{fig:decomp}

% \includegraphics[scale=0.8]{Decomp.png}

% \end{center}
% \end{figure}


\begin{figure}[h]
\begin{center}
\captionsetup{width=0.9\linewidth}
\caption{Shows the trial design, which consists or three arms. Participants will be randomly assigned (at a 1:1:1 ratio) to the CoVideo (Arm 1), an APC video (Arm 2), or no video (Arm 3). Each arm has a list experiment, with participants split (at a 1:1 ratio) into a control or treatment group. }
\label{fig:design}
\includegraphics[scale=0.8]{CoVideoRCT.jpg}
\end{center}
\end{figure}


\clearpage

\subsection*{Supplementary Tables}
\label{sub:SupTables}
\setcounter{table}{0}
\renewcommand{\thetable}{S\arabic{table}}




\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{In each trial arm, participants will be randomized (at a 1:1 ratio) to a control
or treatment group. Both groups will receive five lists. For each list, the control group
will get the first five items only; the treatment group will receive the five items and
the sixth sensitive item, indicated by an asterisk (*). Each list experiment will be
preceded by the question: ``How many of the five/six statements do you agree with? We
don't want to know which ones, just answer how many. This week I will...'' To avoid order
effects, the items in each list will be randomized as well as the presentation order of
the lists. After the list experiments, the five sensitive items will be directly asked,
and preceded by the statement: ``Do you Agree or Disagree with the following statement:
This week I will...'' } 

\label{tab:items}
\footnotesize
\begin{tabular}{p{8cm} | p{7cm}}
\toprule
List 1: Social distancing	& List 2: Wash hands \\
\hline
1. Spend time watching TV	& 1. Clip my toenails \\
2. Do the vacuuming	& 2. Spend time watching movies \\
3. Pick a fight with my partner	& 3. Clean the toilet \\
4. Eat a low sugar diet 	& 4. Smoke marijuana \\
5. Rinse my nose with salt water daily	& 5. Eat fruit daily \\
6. Go out with my friends*	& 6. Wash my hands frequently* \\
\hline
List 3: Clean surfaces & 	List 4: Share utensils \\
\hline
1. Watch a new TV series	& 1. Spend time on the internet \\
2. Spend time gardening by myself 	& 2. Do daily indoor exercises  \\
3. Try to go vegetarian       & 3. Take an online course \\
4. Have alcoholic drinks on at least three evenings 	& 4. Play a prank on my partner \\
5. Catch up on last week's work & 	5. Smoke cigarettes \\
6. Clean kitchen counters after use*	& 6. Clean my dishes after use* \\
\hline
List 5: Stockpiling &	Direct questions list \\
\hline
1. Spend time chatting with my friends online	& 1. Go out with my friends \\
2. Try new cooking recipes 	& 2. Wash my hands frequently \\
3. Watch a pornographic movie	& 3. Clean kitchen counters after use \\
4. Clean all floor surfaces 	& 4. Clean my dishes after us \\
5. Visit the World Health Organization (WHO) website	& 5. Stock up on household supplies for a month \\
6. Stock up on household supplies for a month*	& \\


\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}

\clearpage

\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Shows the items for basic clinical knowledge of COVID-19 spread and the knowledge of
behaviors to prevent the spread of COVID-19. All responses  require True/False responses. } 

\label{tab:know}
\footnotesize
\begin{tabular}{p{14cm}}
\toprule
\hspace{-0.6em}{\textit{Clinical knowledge of COVID-19 spread}} \\
<<echo=FALSE, results='asis'>>=
cknow = data.frame(sapply(cstate, function(x) x[[1]]))
print(xtable(cknow),
  include.colnames=FALSE,
  include.rownames=FALSE,
  hline.after=NULL,
  only.contents=TRUE)
@
\hline
\hspace{-0.6em}{\textit{Knowledge of preventing COVID-19 spread}} \\
<<echo=FALSE, results='asis'>>=
sknow = data.frame(sapply(sstate, function(x) x[[1]]))
print(xtable(sknow),
  include.colnames=FALSE,
  include.rownames=FALSE,
  hline.after=NULL,
  only.contents=TRUE)
@


\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}

\clearpage

\renewcommand{\arraystretch}{1.0} % Tighter
\setlength{\tabcolsep}{4pt}

% \begin{table}[h!]
% \centering
% \begin{threeparttable}

% \caption{Mean estimates and standard errors of  the six list experiment items.} 

% \label{tab:tablist}
% \footnotesize
% \begin{tabular}{l *{12}{C{0.6cm}}}
%   \toprule
%   & \multicolumn{4}{c}{\textbf{Control}} &
%   \multicolumn{4}{c}{\textbf{APC}*}  &
%   \multicolumn{4}{c}{\textbf{CoVideo}} \\ 
%   \cmidrule(r){2-5}  \cmidrule(r){6-9} \cmidrule(r){10-13} 
%   & \multicolumn{2}{c}{\textbf{Control}} & \multicolumn{2}{c}{\textbf{Treatment}}
%   & \multicolumn{2}{c}{\textbf{Control}} & \multicolumn{2}{c}{\textbf{Treatment}}
%   & \multicolumn{2}{c}{\textbf{Control}} & \multicolumn{2}{c}{\textbf{Treatment}} \\
%   \cmidrule(r){2-3}  \cmidrule(r){4-5} \cmidrule(r){6-7} 
%   \cmidrule(r){8-9} \cmidrule(r){10-11} \cmidrule(r){12-13}
%   & \textbf{Mean} & \textbf{SE} 
%   & \textbf{Mean} & \textbf{SE} 
%   & \textbf{Mean} & \textbf{SE} 
%   & \textbf{Mean} & \textbf{SE} 
%   & \textbf{Mean} & \textbf{SE} 
%   & \textbf{Mean} & \textbf{SE} \\
%   \midrule
%   \multicolumn{3}{l}{\textit{In the next week, I will...}$^\dagger$} \\
% <<echo=FALSE, results='asis'>>=
% rownames(tablist) <- sapply(bstate, function(x) x[1])
% print(xtable(tablist, digits=c(1, rep(c(2, 2), 6))),
%       include.rownames=TRUE,
%       include.colnames=FALSE,
%       sanitize.rownames.function=function(x) x,
%       hline.after=NULL,
%       only.contents=TRUE)
% @
% \bottomrule
% \end{tabular}
% \begin{tablenotes} 
% \scriptsize
% \item[*] Attention placebo control. 
% \item[$^\dagger$] The exact english wording of the items: This week, I will$\dots$
% Go out with my friends; Wash my hands frequently; Stock up on household supplies for a
% month; Clean kitchen counters after use; Clean my dishes after use; Watch animated videos made
% by health experts.
% \end{tablenotes}
% \end{threeparttable}
% \end{table}

% \clearpage




\setlength{\tabcolsep}{5pt}

\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Regression estimates of COVID-19 knowledge (18 items) in the Control arm.} 

\label{tab:modc}
\footnotesize
\begin{tabular}{l *{4}{C{1.3cm}}}
\toprule
& Estimate & SE  & t-value & p-value \\
\hline
<<echo=FALSE, results='asis'>>=
print(xtable(reg_all),
  include.colnames=FALSE,
  include.rownames=TRUE,
  hline.after=NULL,
  only.contents=TRUE)
@
\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}


\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Regression estimates of COVID-19 knowledge (18 items) in the CoVideo arm.} 

\label{tab:modc_trt}
\footnotesize
\begin{tabular}{l *{4}{C{1.3cm}}}
\toprule
& Estimate & SE  & t-value & p-value \\
\hline
<<echo=FALSE, results='asis'>>=
print(xtable(reg_all_trt),
  include.colnames=FALSE,
  include.rownames=TRUE,
  hline.after=NULL,
  only.contents=TRUE)
@
\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}


\cleapage

\setlength{\tabcolsep}{5pt}

\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Regression estimates of clinic knowledge of COVID-19 (10 items) in the Control arm.} 

\label{tab:modc}
\footnotesize
\begin{tabular}{l *{4}{C{1.3cm}}}
\toprule
& Estimate & SE  & t-value & p-value \\
\hline
<<echo=FALSE, results='asis'>>=
print(xtable(reg_clinic),
  include.colnames=FALSE,
  include.rownames=TRUE,
  hline.after=NULL,
  only.contents=TRUE)
@
\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Regression estimates of knowledge spread of COVID-19 (8 items) in the Control arm.} 

\label{tab:mods}
\footnotesize
\begin{tabular}{l *{4}{C{1.3cm}}}
\toprule
& Estimate & SE  & t-value & p-value \\
\hline
<<echo=FALSE, results='asis'>>=
print(xtable(reg_spread),
  include.colnames=FALSE,
  include.rownames=TRUE,
  hline.after=NULL,
  only.contents=TRUE)
@
\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Regression estimates of clinic knowledge of COVID-19 (10 items) in the CoVideo arm.} 

\label{tab:modc_trt}
\footnotesize
\begin{tabular}{l *{4}{C{1.3cm}}}
\toprule
& Estimate & SE  & t-value & p-value \\
\hline
<<echo=FALSE, results='asis'>>=
print(xtable(reg_clinic_trt),
  include.colnames=FALSE,
  include.rownames=TRUE,
  hline.after=NULL,
  only.contents=TRUE)
@
\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}


\begin{table}[h!]
\centering
\begin{threeparttable}

\caption{Regression estimates of knowledge spread of COVID-19 (8 items) in the CoVideo arm.} 

\label{tab:mods_trt}
\footnotesize
\begin{tabular}{l *{4}{C{1.3cm}}}
\toprule
& Estimate & SE  & t-value & p-value \\
\hline
<<echo=FALSE, results='asis'>>=
print(xtable(reg_spread_trt),
  include.colnames=FALSE,
  include.rownames=TRUE,
  hline.after=NULL,
  only.contents=TRUE)
@
\bottomrule
\end{tabular}
\begin{tablenotes} 
\scriptsize 
\end{tablenotes}
\end{threeparttable}
\end{table}
