% For LaTeX-Box: root = master.tex
% !Rnw root = master.Rnw
\Sexpr{knitr::set_parent('master.Rnw')}

\clearpage


\subsection*{Figures}
\label{sub:Figures}


\begin{figure}[!ht]
\centering
\includegraphics[scale=0.6]{DataFlow1.png}
\caption{Trial design.}
\label{fig:dataflow}
\end{figure} 



\clearpage

\renewcommand{\note}{%
Mean differences between the CoVideo, Attention Placebo Control (APC), and Control (no
video) are reported with p-values ($N= $\Sexpr{fmt(flow$FinalN)}).  Tot.~Diff.~represents
the total difference in means between the CoVideo and the Control; Att.~Diff.~represents
the attention difference in means between the APC and Control; and Trt.~Diff.~represents
the treatment difference in means between the CoVideo and the APC.  }


\begin{figure}[!ht]
\centering
\includegraphics[scale=0.30]{BehavMeans.png}

\caption{Shows the mean scores for each list experiment by trial arm (CoVideo, APC,
do-nothing) and by control list (Ctrl) and treatment list (Trt). Scores for the treatment
list (Trt) are naturally higher because the treatment list had six items compared with the
five items in the control list. The difference in means between the treatment and control
list represents the prevalence of intent to undertake (or not) the preventive COVID-19
behavior.}

\label{fig:behavmeans}
\end{figure} 



\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.73]{BehavIntent.png}

\caption{Shows the prevalence of intent to undertake preventive
COVID-19 behaviors. Results are shown only for the do-nothing arm ($n = $
\Sexpr{fmt(flow$CtrlN - flow$Ctrl)}), which is a baseline measure of behavioral intent
with social desirability bias removed. For example, for the first list experiment (social
distancing), as shown in Figure \ref{fig:behavmeans}, the treatment list mean is XXXX and
the control list is XXXX for the do-nothing arm. The difference is XXX * 100, which is XXXX\%.} 

\label{fig:behav}
\end{figure} 


\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.72]{BehavDiffs.png}

\caption{Shows the proportion of participants by age and gender that agreed with
statements about COVID-19 behaviors. The proportion represents the difference between the mean
scores in the control list and treatment list of the Control arm ($n = $ \Sexpr{fmt(flow$CtrlN -
flow$Ctrl)}).}

\label{fig:soc}
\end{figure} 

\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.93]{List_1.png}
\label{listreg}
\caption{List experiment adjusting for age group}
\end{figure} 

\clearpage



