% For LaTeX-Box: root = master.tex
% !Rnw root = master.Rnw
\Sexpr{knitr::set_parent('master.Rnw')}

\clearpage


\subsection*{Figures}
\label{sub:Figures}


\begin{figure}[!ht]
\centering
\includegraphics[scale=0.6]{DataFlow1.png}
\caption{Trial design.}
\label{fig:dataflow}
\end{figure} 



\clearpage

\renewcommand{\note}{%
Mean differences between the CoVideo, Attention Placebo Control (APC), and Control (no
video) are reported with p-values ($N= $\Sexpr{fmt(flow$FinalN)}).  Tot.~Diff.~represents
the total difference in means between the CoVideo and the Control; Att.~Diff.~represents
the attention difference in means between the APC and Control; and Trt.~Diff.~represents
the treatment difference in means between the CoVideo and the APC.  }


\begin{figure}[!ht]
\centering
\includegraphics[scale=0.30]{BehavMeans.png}

\caption{Shows the mean scores for each list experiment by trial arm (E-E video, APC
video, do-nothing) and by control list (Ctrl) and treatment list (Trt). Scores for the treatment
list are higher because the treatment list has six items and the
control list has five items. The difference between the treatment and control
means represents the prevalence of intent to undertake  the preventive COVID-19
behavior.  For example, for the first list experiment
 in the E-E video arm (`this week I will go out with friends'), let 
\(\bar{T}^{ee}\) $=$ \Sexpr{fmt(ddat[["SocialDist"]][["est", "trttrt"]], 2)}  be the
treatment mean and let 
\(\bar{C}^{ee}\) $=$ \Sexpr{fmt(ddat[["SocialDist"]][["est", "trtctr"]], 2)} be the
control mean. The prevalence is then
\(P^{ee} = (\bar{T}^{ee} - \bar{C}^{ee}) \times 100 = 
(\Sexpr{fmt(ddat[["SocialDist"]][["est", "trttrt"]], 2)} -
\Sexpr{fmt(ddat[["SocialDist"]][["est", "trtctr"]], 2)}) \times 100 = 
\Sexpr{fmt(ddat[["SocialDist"]][["est", "trtdif"]]*100, 1)} \).   
Similarly, the prevalence for the APC arm is \(P^{apc} = (\bar{T}^{apc} - \bar{C}^{apc}) \times 100 =
(\Sexpr{fmt(ddat[["SocialDist"]][["est", "apctrt"]], 2)} -
\Sexpr{fmt(ddat[["SocialDist"]][["est", "apcctr"]], 2)}) \times 100 = 
\Sexpr{fmt(ddat[["SocialDist"]][["est", "apcdif"]]*100, 1)} \).}   

\label{fig:behavmeans}
\end{figure} 





\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.72]{BehavDiffs.png}

\caption{Shows the prevalence of behavioral intent for each of the five list experiments
with 95\% CIs. Included is the total and content effects of the E-E video, along with
their 95\% CIs and p-values. 
Using the example from Figure \ref{fig:behavmeans}, the content effect is calculated as
\(\bar{D}^{Cont} = P^{ee} - P^{apc} = 
\Sexpr{fmt(ddat[["SocialDist"]][["est", "trtdif"]]*100, 1)} -
\Sexpr{fmt(ddat[["SocialDist"]][["est", "apcdif"]]*100, 1)} = 
\Sexpr{fmt(ddat[["SocialDist"]][["est", "trteq"]]*100, 1)} \).   
}



\label{fig:soc}
\end{figure} 



\clearpage

\begin{figure}[!ht]
\centering
\includegraphics[scale=0.73]{BehavIntent.png}

\caption{Shows the prevalence of behavioral intent to undertake preventive COVID-19
practices.  Results are shown only for the do-nothing arm ($n = $ \Sexpr{fmt(flow$CtrlN -
flow$Ctrl)}), which is a baseline measure of behavioral intent with social desirability
bias removed. For example, for the first list experiment (social distancing) in the
do-nothing arm (see Figure \ref{fig:behavmeans}), the difference between the treatment list
(mean $=$ \Sexpr{fmt(ddat[["SocialDist"]][["est", "ctrtrt"]], 2)}) and the control list
(mean $=$ \Sexpr{fmt(ddat[["SocialDist"]][["est", "ctrctr"]], 2)}) is
\Sexpr{fmt(ddat[["SocialDist"]][["est", "ctrdif"]], 3)}, which (after multiplying by 100) is
the prevalence of participants that intended to go out with friends despite social
distancing norms.}

\label{fig:behav}
\end{figure} 



\begin{figure}[!ht]
\centering
\includegraphics[scale=0.93]{List_1.png}
\label{listreg}
\caption{List experiment adjusting for age group}
\end{figure} 

\clearpage



