% !Rnw root = master.Rnw
%! TEX root = master.tex
\Sexpr{knitr::set_parent('master.Rnw')}



\subsection*{Introduction}

In the absence of a vaccine, public health efforts to contain the novel coronavirus
(COVID-19) have relied on preventive human behaviours such as quarantining, social
distancing, and hand sanitation, among others.  Current efforts could therefore benefit
from the rapid distribution of entertainment-education (E-E) materials about preventive
COVID-19 behaviors through social media channels to a global audience.\citep{Hahn2020,
Block2020} To this end, we have designed a short, animated E-E video that describes how
COVID-19 is spread (airborne, physical contact), and recommends best practices to prevent
its spread (e.g., staying at home, not congregating in public spaces, and sanitizing hands
and surfaces).\citep{Adam2020} The E-E video was released on Stanford Medicine's YouTube
channel on March 21, 2020 and within 10 days reached 332,000 views on YouTube, 220,000
views on Instagram, 294,000 views on Facebook, and 402,000 views on Twitter, with a
cumulative count of 1.2 million views.\citep{Adam2020} 


To evaluate the E-E video's effectiveness, we randomized \Sexpr{fmt(flow$In)} online
participants from the United States of America (USA), Mexico, the United Kingdom (UK),
Germany, and Spain to the E-E intervention arm, an attention placebo control (APC) video
arm, and a do-nothing (no video) arm.\citep{Vandormael2020b} One challenge of our
randomized controlled trial (RCT) is that, in the era of COVID-19, participants will be
primed to give socially desirable responses to questions on the behavioral prevention of
the coronavirus.  To remove social desirability bias, we nested a list randomization
experiment in each trial arm and asked participants to indirectly agree (or disagree) with
statements about their behavioral intent toward preventive COVID-19 practices. We also asked
direct verions of these statements, thereby enabling us to quantify the magnitude of
social desirability bias.  Our study results will inform the design of future E-E videos
to disseminate evidence-based health recommendations related to COVID-19 as well as other
public health emergencies.   



\subsection*{Methods}

\paragraph{Study design and participants} 

This was a multi-site, parallel group, RCT comparing the effectiveness of the E-E video
against an attention placebo control (APC) video and do-nothing.\citep{Vandormael2020b} We
used an online platform called Prolific Academic (\url{https://www.prolific.co}) to enroll
participants on a ``first come, first served'' basis. Participant eligibility included
being  18 to 59 years of age (male, female, or other), having residence in the USA, the UK,
Germany, Spain, or Mexico, and having proficiency in English, German, or Spanish. The
trial was hosted and deployed on Gorilla (\url{www.gorilla.sc}), which is a cloud platform
that provides versatile tools to undertake online, experimental, and behavioural
research.\citep{Anwyl-Irvine2020} The study and its outcomes were registered at the German
Clinical Trials Register (www.drks.de) on May 12th, 2020: \#DRKS00021582. Ethical approval
was obtained from the Stanford University IRB on April 12, 2020, \#55820.    

\paragraph{Randomization and masking}

Randomization was at a 1:1:1 ratio for the three arms of the trial. In each arm,
randomization was  at a 1:1 ratio to the treatment and control lists.  Because Prolific
Academic handled the interaction between the study investigators and participants, the
participants were completely anonymous to the study investigators. Participants
self-responded to the survey questions and self-submitted their responses anonymously on
the Gorilla platform. The study investigators were blinded to the group
allocation.\citep{Vandormael2020b} 


\paragraph{Procedures}

Participants began the online study on the Gorilla platform by answering basic demographic
questions about their age, sex, primary language, country of residence, and highest
education completed.

Participants were  then randomly assigned by Gorilla to the E-E video, APC video, or
the do-nothing arm. We have The APC is also a wordless, animated video with the same duration as the
E-E video.  Its content describes how small choices become actions, which become habits,
which become a way of life (\url{https://www.youtube.com/watch?v=_HEnohs6yYw}).  We
included an APC to account for possible attention effects elicited by the video medium.
APC conditions should mimic the ``inactive'' components of an intervention—the effect of
watching the video---while not containing any of the ``active'' intervention
components---the content delivered by the video.\citep{Freedland2011} We did not make the
assumption that the E-E video is better than nothing (i.e., no video). It is possible that
the E-E video could motivate reactance to our COVID-19 prevention
message.\citep{Dillard2005,Miller2007, Richards2015} 


After completing the intervention (E-E video, APC, do-nothing), Gorilla then randomized
participants to five list experiments.\citep{Vandormael2020b} We used a list experiment to
reduce socially desirable answers to the behavioural intent questions.\citep{Kramon2019,
Corstange2009, Glynn2013} For each experiment, the control group received a list of five
items that were unrelated to COVID-19. For example, in the first list experiment we asked:
``How many of the five statements do you agree with? We don't want to know which ones,
just answer how many: 1. Spend time watching TV, 2. Do the vacuuming, 3.  Pick a fight
with my partner, 4. Eat a low sugar diet, 5. Rinse my nose with salt water daily.''  The
treatment group received the same five items and one additional `sensitive' item: ``Go out
with my friends'', which indicates behavioral intent to social distance (or not) during
lockdown resitrictions. The other four list experiments covered the topics of washing
hands, cleaning surfaces, sharing utensils, and stockpiling essential goods. We designed
the list experiments in line with best practices.\citep{Glynn2013}

After the list experiments, participants were asked the five sensitive items directly. For
example, ``Please answer True or False if you agree with the following statement: This
week I will go out with my friends.'' To ensure post-trial access to
treatment,\citep{Doval2015} participants in the APC and do-nothing arm could choose to
watch the E-E video at the end of the study. 


\paragraph{Statistical analysis}

We also summarized the participant characteristics by obtaining means and standard
deviations of age, gender, primary language, country of residence, and education status.

The primary outcome was the difference in behavioral intent toward preventive COVID-19
behaviors. For each list experiment, we calculated the mean score for the control list
(min. $=$ 0, max. $=$ 5), denoted by \(\bar{C}_i \), and the mean score for the treatment
list (min.~$=$ 0, max. $=$ 6), denoted by \(\bar{T}_i \), for the \(i\)th list experiment
\((i=1,\dots, 5)\). Let the superscripts \(^{ee}\) denote the E-E CoVideo, \(^{apc}\)
denote the APC, and \(^{no}\) denote the do-nothing arms, and let \(k\) denote the \(k\)th
trial arm (\(k \in [^\text{ee,} ^\text{apc,} ^\text{no}]\)).  For list experiment $i$ and
trial arm $k$,  we then estimated the prevalence of behavioral intent, denoted by
\(P_{i}^k\), as the difference between the treatment and control, such that  \(P_{i}^k=
(\bar{T}_{i}^k- \bar{C}_{i}^k) \times 100\). From these estimates, we calculated the
total, content, and attention effects of the CoVideo.  Let \(D_i^{Tot}\) denote the total effect,
which is estimated by \(P_{i}^{ee}-P_{i}^{no}\); let \(D_i^{Cont}\) denote the content
effect, which is estimated by \(P_{i}^{ee}-P_{i}^{apc}\); and let \(D_i^{Att}\) denote
the attention effect, which is estimated by \(P_{i}^{apc}-P_{i}^{no}\).  These analyses
are analogous to difference-in-difference analyses, which we implemented by specifying
the main and interaction terms in an ordinary least squares (OLS) regression model.
The OLS equation for the \(i\)th list experiment is given as: 

\begin{equation}
y = b_0 + b_1 \text{VideoArm} + b_2 \text{TreatList} + b_3 (\text{VideoArm} \times
\text{TreatList}), 
\end{equation}

where \(y\) is the number of statements in the list that the participant agreed with,
VideoArm indicates the \(k\)th arm, and TreatList indicates assignment to the treatment or
control list. We calculated  standard errors, 95\% confidence interals, and p-values for
linear combinations of coefficients from the OLS model. 

To evaluate how behavioral intent varies by age, we used a nonlinear least-squares
estimator for the list experiment response and covariate data. Designed by Blaire
and Imai,\citep{Blair2012} the model assumes that the response has a Poisson-Binomial
distribution. In addition, we calculated the magnitude of social desirability bias. We did
this first by calculating the prevalence of True responses to the five sensitive
questions, which we asked directlt. We then obtained the difference of the indirect and
direct responses, which is the bias. 


Statistical analyses were performed with R software version 4.2, using the
\texttt{lm}, \texttt{linearHypothesis}, \texttt{ictreg} commands from the \texttt{stats},
\texttt{car}, and \texttt{list} packages, respectively.


\paragraph{Role of the funding source}

The funder of the study had no role in study design, data collection, data analysis, data
interpretation, or writing of the report. The corresponding author had full access to all
the data in the study and had final responsibility for the decision to submit for
publication.

\subsection*{Results}


Between \Sexpr{res$dates[1]} and \Sexpr{res$dates[2]}, we enrolled \Sexpr{fmt(flow$In)}
participants through the Prolific Academic platform. A total of  \Sexpr{fmt(flow$In -
flow$Start)} participants were randomly assigned to the E-E video
(\Sexpr{fmt(flow$CoVidN)}), APC (\Sexpr{fmt(flow$APCN)}), and do-nothing
(\Sexpr{fmt(flow$CtrlN)}) arms (Figure \ref{fig:dataflow}).  Between recruitment and
randomization, \Sexpr{flow$Start} participants were lost and  after randomization another
\Sexpr{flow$Ctrl} (do-nothing), \Sexpr{flow$APC} (APC), and \Sexpr{flow$Trt} (E-E video)
were lost for unknown reasons (possibly due  technical reasons such as a lost
internet connection, issues with linking to the video host, YouTube, server complications,
etc).  A total of \Sexpr{fmt(flow$FinalN)} participants completed the trial and
contributed data to the final analysis. 

The majority of participants  reported their residence in the UK
(\Sexpr{res$ctry["United Kingdom"]}\%) or the USA
(\Sexpr{res$ctry["United States"]}\%), and \Sexpr{res$lan["EN"]}\% of participants reported English as their first
language.  The sample was relatively well-educated, with \Sexpr{sum(res$educ[c(3,4)])}\%
having some college education or higher (BA, MA equivalent or PhD).  Table \ref{tab:tab1}
shows the percentage of participants in each arm and treatment list by age, gender, country of residence,
educational status, and primary language. 

<<echo=FALSE>>=
wash <- behav["Wash", ]
dish <- behav["CleanDishes", ]
kitch <- behav["CleanSurfaces", ]
stock <- behav["StockPile", ]
soc <- behav["SocialDist", ]
@


Figure \ref{fig:behavmeans} shows the means scores for the five list experiments by trial
arm and treatment group.  These mean scores can be used to calculate the prevalence of
behavioral intent (with 95\% confidence intervals [CI]) for the five preventive COVID-19
behaviors. In addition, the mean scores can be used to estimate the total effect (the
difference between the E-E video and do-nothing) and content effect (the difference
between the E-E video and the APC) along with their 95\% CIs and p-values. These results are
shown in Figure \ref{fig:behav}, which includes an example calculation.  Results show that
participants in the CoVideo arm had lower behavioral intent to go out with friends when
compared with the APC (content effect $=$ \Sexpr{fmt(ddat[["SocialDist"]][["est",
"trteq"]], 3)}, \Sexpr{pfmt(ddat[["SocialDist"]][["pval", "trteq"]])}) and do-nothing
(total effect $=$\Sexpr{fmt(ddat[["SocialDist"]][["est", "toteq"]], 3)},
\Sexpr{pfmt(ddat[["SocialDist"]][["pval", "toteq"]])}) arms. Participants in the CoVideo
arm also had lower behavioral intent to stockpile goods, when compared with the APC
(content effect $=$ \Sexpr{fmt(ddat[["StockPile"]][["est", "trteq"]], 3)},
\Sexpr{pfmt(ddat[["StockPile"]][["pval", "trteq"]])}) and do-nothing (total effect
$=$\Sexpr{fmt(ddat[["StockPile"]][["est", "toteq"]], 3)},
\Sexpr{pfmt(ddat[["StockPile"]][["pval", "toteq"]])}) arms. For cleaning dishes after use,
participants in the CoVideo arm had a higher behavioral intent than the APC (content
effect $=$ \Sexpr{fmt(ddat[["CleanDishes"]][["est", "trteq"]], 3)},
\Sexpr{pfmt(ddat[["CleanDishes"]][["pval", "trteq"]])}) and do-nothing (total effect
$=$\Sexpr{fmt(ddat[["CleanDishes"]][["est", "toteq"]], 3)},
\Sexpr{pfmt(ddat[["CleanDishes"]][["pval", "toteq"]])}) arms. The E-E video had no impact
on behavioral intent to prevent COVID-19 spread by cleaning kitchen counters after use. 




Figure 6 shows the di?erences in behaviora intent by age and gender for each of the ?ve statements.
For the social distancing statement, younger men (aged 18-24 years) and older men (aged 45-59
years) were more likely than their female counterparts to go out with friends . With the exception 205
of the 45?54 year age group, more men intended to stockpile household supplies for the next month
when compared with women. Older men and women were more likely to clean their dishes after
use to prevent the spread of COVID-19. Most participants agreed that they will wash their hands
frequently in the next week.


To measure baseline intent toward preventive COVID-19 behaviors,
we obtained the difference between the treatment and control list for the do-nothing arm.
Figure \ref{fig:behav} shows these results.  Participants had high intent to wash their
hands frequently (\Sexpr{wash$ctrdif.est}\%, 95\% CI: \Sexpr{wash$ctrdif.lb}--\Sexpr{wash$ctrdif.ub}\%), with
lower intent to clean dishes after use (\Sexpr{dish$ctrdif.est}\%, 95\% CI:
\Sexpr{dish$ctrdif.lb}-\Sexpr{dish$ctrdif.ub}\%) and clean kitchen counters after use
(\Sexpr{kitch$ctrdif.est}\%, 95\% CI: \Sexpr{kitch$ctrdif.lb}--\Sexpr{kitch$ctrdif.ub}\%). Despite advice not
to, \Sexpr{stock$ctrdif.est}\% of participants intended to stockpile household supplies for a month
(95\% CI: \Sexpr{stock$ctrdif.lb}--\Sexpr{stock$ctrdif.ub}\%) and \Sexpr{soc$ctrdif.est}\% said they would go
out with friends under lockdown restrictions (95\% CI:
\Sexpr{soc$ctrdif.lb}--\Sexpr{soc$ctrdif.ub}\%).




\subsection*{Discussion}



\paragraph{Contributors}

% AV wrote the paper and undertook the statistical analysis. TB, MA, MG, and JG provided
% comments and feedback. MA designed, produced, and created the E-E video. TB and AV designed
% the trial. AV, TB, MA, and MG contributed to the questionnaire development.


\paragraph{Declaration of interests}
We declare no competing interests. 

\paragraph{Acknowledgments}
TB is funded by the Alexander von Humboldt University Professor Prize.

