% !Rnw root = master.Rnw
%! TEX root = master.tex
\Sexpr{knitr::set_parent('master.Rnw')}



\subsection*{Introduction}

In the absence of a vaccine, behaviours such as social distancing and hand sanitation
(among others) are critical for reducing the spread of the novel coronavirus (COVID-19).
To this end, we have designed a short, animated entertainment-education (E-E) video to
improve intent toward preventive COVID-19 behaviours.\citep{Vandormael2020b} The E-E video
describes how the novel coronavirus is spread (airborne, physical contact), and recommends
best practices to prevent or reduce the spread of COVID-19 (staying at home, not
congregating in public spaces, and sanitizing hands and surfaces). It also covers the mass
media coverage of the epidemic and a subplot about the stockpiling of essential goods
(\url{https://www.youtube.com/watch?v=rAj38E7vrS8}).\citep{Adam2020} An effective public
health response to COVID-19 could benefit from the rapid distribution of E-E material
through social media channels to a global audience.\citep{Hahn2020, Block2020} 


The E-E video was released on Stanford Medicine's YouTube channel on March 21, 2020 and
reached 332,000 views on YouTube, 220,000 views on Instagram, 294,000 views on Facebook,
and 402,000 views on Twitter, with a cumulative count of 1.2 million views within 10
days.\citep{Adam2020} Using a randomized controlled trial (RCT), we evaluate the E-E
video's effectiveness to improve behavioral intent toward preventive COVID-19 practices.
We randomized \Sexpr{fmt(flow$In)} online participants from the United States of America
(USA), Mexico, the United Kingdom (UK), Germany, and Spain to the E-E video, an attention
placebo control (APC), and do-nothing (no video). We also nested a list randomization
experiment in each trial arm to remove social desirability bias from the behavioral intent
responses.  Our study results will inform the design of future E-E videos to disseminate
evidence-based health recommendations related to COVID-19 as well as other public health
emergencies.   



\subsection*{Methods}

\paragraph{Study design and participants} 

This was a multi-site, parallel group, RCT comparing the effectiveness of the E-E video
against an attention placebo control (APC) video and do-nothing.\citep{Vandormael2020b} We
used an online platform called Prolific Academic (\url{https://www.prolific.co}) to enroll
participants on a ``first come, first served'' basis. Participant eligibility included
being  18 to 59 years of age (male, female, or other), having residence in the USA, the UK,
Germany, Spain, or Mexico, and having proficiency in English, German, or Spanish. The
trial was hosted and deployed on Gorilla (\url{www.gorilla.sc}), which is a cloud platform
that provides versatile tools to undertake online, experimental, and behavioural
research.\citep{Anwyl-Irvine2020} The study and its outcomes were registered at the German
Clinical Trials Register (www.drks.de) on May 12th, 2020: \#DRKS00021582. Ethical approval
was obtained from the Stanford University IRB on April 12, 2020, \#55820.    

\paragraph{Randomization and masking}

Randomization was at a 1:1:1 ratio for the three arms of the trial. In each arm,
randomization was  at a 1:1 ratio to the treatment and control lists.  Because Prolific
Academic handled the interaction between the study investigators and participants, the
participants were completely anonymous to the study investigators. Participants
self-responded to the survey questions and self-submitted their responses anonymously on
the Gorilla platform. The study investigators were blinded to the group
allocation.\citep{Vandormael2020b} 


\paragraph{Procedures}

Participants began the online study on the Gorilla platform by answering basic demographic
questions about their age, sex, primary language, country of residence, and highest
education completed.

Participants were  then randomly assigned by Gorilla to the E-E video, APC video, or
do-nothing arm.  The APC is also a wordless, animated video with the same duration as the
E-E video.  Its content describes how small choices become actions, which become habits,
which become a way of life (\url{https://www.youtube.com/watch?v=_HEnohs6yYw}).  We
included an APC to account for possible attention effects elicited by the video medium.
APC conditions should mimic the ``inactive'' components of an intervention—the effect of
watching the video---while not containing any of the ``active'' intervention
components---the content delivered by the video.\citep{Freedland2011} We did not make the
assumption that the E-E video is better than nothing (i.e., no video). It is possible that
the E-E video could motivate reactance to our COVID-19 prevention
message.\citep{Dillard2005,Miller2007, Richards2015} 


After completing the intervention (E-E video, APC, do-nothing), Gorilla then randomized
participants to five list experiments.\citep{Vandormael2020b} We used a list experiment to
reduce socially desirable answers to the behavioural intent questions.\citep{Kramon2019,
Corstange2009, Glynn2013} For each experiment, the control group received a list of five
items that were unrelated to COVID-19. For example, in the first list experiment we asked:
``How many of the five statements do you agree with? We don't want to know which ones,
just answer how many: 1. Spend time watching TV, 2. Do the vacuuming, 3.  Pick a fight
with my partner, 4. Eat a low sugar diet, 5. Rinse my nose with salt water daily.''  The
treatment group received the same five items and one additional `sensitive' item: ``Go out
with my friends'', which indicates behavioral intent to social distance (or not) during
lockdown resitrictions. The other four list experiments covered the topics of washing
hands, cleaning surfaces, sharing utensils, and stockpiling essential goods. We designed
the list experiments in line with best practices.\citep{Glynn2013}

To ensure post-trial access to treatment,\citep{Doval2015} participants in the
APC and do-nothing arm could choose to watch the E-E video at the end of the
study. 


\paragraph{Statistical analysis}


The primary outcome was the difference in between in behavioral intent between the trial
arms.  For each list experiment, we calculated the mean score for the control list,
denoted by \(\bar{C}_i \), and the mean score for the treatment list, denoted by
\(\bar{T}_i \), for the \(i\)th list experiment \((i=1,\dots, 5)\). We then estimated the
difference between the treatment and control list for each trial arm, denoted by \(D_{ik}=
\bar{T}_{ik}- \bar{C}_{ik}\), for the ith treatment list and \(k\)th trial arm, where \(k
\in [v,a,c]\). Let \(DD_i^T\) denote the total effect, which is estimated by
\(D_{iv}-D_{ic}\); let \(DD_i^C\) denote the content effect, which is estimated by
\(D_{iv}-D_{ia}\); and let \(DD_i^A\) denote the attention effect, which is estimated by
\(D_{ia}-D_{ic}\).  These analyses are analogous to difference-in-difference analyses,
which can be implemented by specifying the appropriate main and interaction terms in an
ordinary least squares (OLS) regression.  We also summarized the
participant characteristics by obtaining means and standard deviations of age, gender,
primary language, country of residence, and education status.  Statistical analyses were
performed with R software version 4.2.


\paragraph{Role of the funding source}

The funder of the study had no role in study design, data collection, data analysis, data
interpretation, or writing of the report. The corresponding author had full access to all
the data in the study and had final responsibility for the decision to submit for
publication.

\subsection*{Results}


Between \Sexpr{res$dates[1]} and \Sexpr{res$dates[2]}, we enrolled \Sexpr{fmt(flow$In)}
participants through the Prolific Academic platform. A total of  \Sexpr{fmt(flow$In -
flow$Start)} participants were randomly assigned to the E-E video
(\Sexpr{fmt(flow$CoVidN)}), APC (\Sexpr{fmt(flow$APCN)}), and do-nothing
(\Sexpr{fmt(flow$CtrlN)}) arms (Figure \ref{fig:dataflow}).  Between recruitment and
randomization, \Sexpr{flow$Start} participants were lost and  after randomization another
\Sexpr{flow$Ctrl} (do-nothing), \Sexpr{flow$APC} (APC), and \Sexpr{flow$Trt} (E-E video)
were lost for unknown reasons (possibly due  technical reasons such as a lost
internet connection, issues with linking to the video host, YouTube, server complications,
etc).  A total of \Sexpr{fmt(flow$FinalN)} participants completed the trial and
contributed data to the final analysis. 

The majority of participants  reported their residence in the UK
(\Sexpr{res$ctry["United Kingdom"]}\%) or the USA
(\Sexpr{res$ctry["United States"]}\%), and \Sexpr{res$lan["EN"]}\% of participants reported English as their first
language.  The sample was relatively well-educated, with \Sexpr{sum(res$educ[c(3,4)])}\%
having some college education or higher (BA, MA equivalent or PhD).  Table \ref{tab:tab0}
shows the percentage of participants in each arm by age, gender, country of residence,
educational status, and primary language. 



\subsection*{Discussion}



\paragraph{Contributors}

% AV wrote the paper and undertook the statistical analysis. TB, MA, MG, and JG provided
% comments and feedback. MA designed, produced, and created the E-E video. TB and AV designed
% the trial. AV, TB, MA, and MG contributed to the questionnaire development.


\paragraph{Declaration of interests}
We declare no competing interests. 

\paragraph{Acknowledgments}
TB is funded by the Alexander von Humboldt University Professor Prize.

